### ISSUE TITLE
Store plot history within a table

### ISSUE THREAD

**Issue by mDibyo** [data-8/datascience#137]
In addition to making it easier to manipulate the plots, this will also make it easier to test the plotting functions. See discussion in #132.

**Comment by SamLau95** [comment]
I actually am liking this idea more now because without this we can't test whether students have called hist properly during lab and projects.

**Comment by papajohn** [comment]
It's too bad that the notebook will then display the object using `<...>` syntax before the visualization. We could instead store the history of plots as a field in the table. Thoughts?
