### ISSUE TITLE
Table.hist should default to normed=True

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#148]
Ani says things in lecture like "in this class histograms are always normed".  So, let's make the default do the right thing: the default should be normed=True, so we don't need to repeat it (and students don't need to remember it).

**Comment by a-adhikari** [comment]
Thank you! I think John suggested this a while ago too.
Ani

**Comment by deculler** [comment]
Seems like this is an important question of terminology.  Doesn't this
choice make it a discrete distribution rather than a histogram.  There is a
related technical issue that comes up in boot strapping when we start
drawing samples from these whatever they are called.  In general a
histogram has bins.  Whereas when we start sampling we are drawing from a
discrete distribution, i.e, the bins are discrete values not ranges.  I
realize that I'm the nubee here but I would find this sort of inconsistency
very frustrating.

As I poke around now at the various definitions of histogram they do convey
discretization of a distribution.  So the counts per bin that everyone
learns in school and plots in excels a column chart is the aberration.  So
what is that thing called?

On Saturday, November 7, 2015, a-adhikari <notifications@github.com> wrote:

> Thank you! I think John suggested this a while ago too.
> Ani
>
> > On Nov 6, 2015, at 10:39 AM, davidwagner <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Ani says things in lecture like "in this class histograms are always
> normed". So, let's make the default do the right thing: the default should
> be normed=True, so we don't need to repeat it (and students don't need to
> remember it).
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsten/datascience/issues/148#issuecomment-154510547>.
>


-- 
David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by a-adhikari** [comment]
So the counts per bin that everyone
learns in school and plots in excels a column chart is the aberration. So
what is that thing called?
A mistake?

If anything, histograms turn discrete distributions into continuous ones:
mixtures of uniform distributions over the bins. The flat tops assume that
the proportion in the bin is uniformly smeared across the bin.

A histogram is essentially a density "curve", representing proportions by
areas. Nothing else is a histogram, to my knowledge. Those other things
might be bar graphs if you think of the bins as categorical.

Ani

On Fri, Nov 6, 2015 at 6:10 PM, David Culler <notifications@github.com>
wrote:

> Seems like this is an important question of terminology. Doesn't this
> choice make it a discrete distribution rather than a histogram. There is a
> related technical issue that comes up in boot strapping when we start
> drawing samples from these whatever they are called. In general a
> histogram has bins. Whereas when we start sampling we are drawing from a
> discrete distribution, i.e, the bins are discrete values not ranges. I
> realize that I'm the nubee here but I would find this sort of inconsistency
> very frustrating.
>
> As I poke around now at the various definitions of histogram they do convey
> discretization of a distribution. So the counts per bin that everyone
> learns in school and plots in excels a column chart is the aberration. So
> what is that thing called?
>
> On Saturday, November 7, 2015, a-adhikari <notifications@github.com>
> wrote:
>
> > Thank you! I think John suggested this a while ago too.
> > Ani
> >
> > > On Nov 6, 2015, at 10:39 AM, davidwagner <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > Ani says things in lecture like "in this class histograms are always
> > normed". So, let's make the default do the right thing: the default
> should
> > be normed=True, so we don't need to repeat it (and students don't need to
> > remember it).
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dsten/datascience/issues/148#issuecomment-154510547
> >.
> >
>
>
> --
> David E. Culler
> Friesen Professor of Computer Science
> Electrical Engineering and Computer Sciences
> University of California, Berkeley
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsten/datascience/issues/148#issuecomment-154598422>.
>



-- 
Ani Adhikari
Teaching Professor
Department of Statistics
University of California, Berkeley

**Comment by mijordan3** [comment]
I think that David raises a very good issue, one that needs further
discussion.  Indeed, I have been hoping to reconvene last spring's
DS 8 planning committee at the end of the term (RRR week?) to have a
post-mortem on the class that focuses on intellectual issues such as these.
Particularly given that a significant fraction of the committee attended the
lectures, such a post-mortem should be useful and fun.

Given that this class is so heavily focused on sampling and resampling,
it's important that discrete probability distributions are front and
center.  Now, given that we're not basing the course on probability,
this is a bit of a challenge!

Ani's right that a histogram is generally viewed as a *density* in the
literature.  (More precisely, it's viewed as a *density estimate*).
It is an object that if integrated from left to right yields a cumulative
distribution function that is piecewise linear.  The x-axis represents
the real numbers in this case.

Adopting that interpretation of a histogram, the notion of "sampling from
a histogram" means that one can obtain any real number.  The real numbers in
a given bin all have equal probability of being chosen.  (Actually, that
probability
is zero---they all have zero probability of being chosen!  But somehow one
of
them does get chosen...  Understanding sampling from densities is
non-trivial
and requires some serious calculus).

So, clearly, we can't really ever say "we sample from a histogram" in
this class if we're using the generally accepted definition of a histogram
and if we have in mind the notion of sampling from a discrete distribution.

Here we face the challenge of one visual representation naturally being used
in different ways for the descriptive side of the course and the
inferential side of the
course.

It would also be quite possible, although nonstandard, to view a histogram
as a representation of a discrete probability distribution, where the height
associated with a bin represents a mass that is located at the center of
the bin.  In which case, "sampling from a histogram" would be the intuitive
notion of sampling from a discrete distribution; no calculus needed.

This is actually what is done in the quantization literature, where an
algorithm such as K-means returns a partition (e.g., in one dimension, a
set of adjacent bins) *and* a set of centroids.

An alternative to the histogram representation involves putting a bit of
space between the bars, and the resulting object is generally called a
"bar graph" or a "bar chart".  Here it's clear that one doesn't have a
density in mind.  But these representations generally seem to be used mainly
with categorical data, where the x-axis doesn't represent the real line
anymore, and the category labels are not embedded in the reals.  The labels
are spread uniformly along the x-axis.  Somewhat non-traditionally, one
could
also allow numerical labels that are considered to be embedded in the reals,
in which case one would get bars at non-uniform points in general.

A third representation which is used in mathematical discussions but not
so much in data visualization is the "ball-and-stick" representation of a
discrete probability distribution.  Given a set of atomic masses, one places
sticks vertically at the locations of those masses, and a ball on top for
visual clarity.  The height of the sticks represents the probability masses
at the atoms.

Starting with a data set, one can plot the "empirical distribution" of the
data using this third representation, in which case one gets a set of masses
all of height 1/n.  Resampling from this distribution, one obtains a new
picture
in which the masses are at the same locations, but the heights are 0/n,
1/n, 2/n, etc.

One can also start to aggregate, by forming bins.  If one retains the
ball-and-stick
representation, then all that's happening is that the stick height is the
sum of
the heights of those atoms falling into the bin.  If one goes to the
histogram
representation, one has smeared that total height out into a uniform
density over
the bin.  Visually this is fine, even appealing, but mathematically one is
now in
different waters unless one changes the standard definition.

Ani's lectures may well have navigated all of this perfectly, but I do
think,
especially given David's query, that it probably warrants some discussion.

Visual representations such as histograms and bar graphs have mainly been
developed
for the purposes of descriptive statistics.  For us, given that the
inferential content
of the course is so heavily built on resampling, we need visual
representations
that teach resampling ideas without clutter or confusion, and this puts new
requirements on the visual representations, requirements that may or may not
align entirely with their descriptive usages.

M

**Comment by deculler** [comment]
Good discussion.  Part of what got me thinking about these things was that
I started to go write Table.sample_hist which would treat a table such as
one returned from Table.bin as a great histogram and sample from it.  But
in addition to needing to smear non-unit bins you may also have multiple
columns.  If sample from them independently you may get tuples that are
unrepresentative if the population that is summarized in the table, but if
you treat it as sampling rows, ie, dependent it is also likely to be
unrepresentative.  No matter what you do you are at risk of doing something
silly.  I imagine there is a body of thought on the "multivariable" case.

**Comment by mijordan3** [comment]
Yes, there's a (huge) literature on the multivariable setting.  Graphical
models is one general formalism for
treating the multivariable case.  Sampling columns independently is rarely
a reasonable thing to do; it's
generally only done in the context of a null hypothesis that asserts
independence.  Sampling rows does
retain the dependencies in the data and is thus generally a reasonable
thing to do (when the data can be
assumed to be sampled randomly from the population).   The most general
case is when there are dependencies
in both dimensions; e.g., with multivariate time series.  The dependency
along the rows is nonetheless often
simpler than along the columns.

M

**Comment by papajohn** [comment]
I don't think we ever sample from a histogram in this course, and sampling from any continuous distribution at all only happens at the very end. The meat of the inference section is about permuting and resampling discrete collections of observations that haven't been aggregated or binned. I think we'll keep it that way, and let histograms serve strictly as a visualization instead of a computational object used for downstream processing.
