### ISSUE TITLE
Proper versioning, changelogs, and releasing

### ISSUE THREAD

**Issue by SamLau95** [data-8/datascience#156]
To be frank, this is an issue that should have been addressed before the semester started but better late than never!

Our workflow w.r.t. versioning has worked like this up to this point:

1. Work work work.
2. When students need to receive the updates, bump up the minor version
(eg. `0.3.2 -> 0.3.3`) and release on Pypi.
3. Repeat.

Ideally, our workflow would look more like:

1. Add features to master, being careful not to introduce backwards-incompatible
changes until major releases (eg. `0.6.1 -> 1.0.0`).
2. After each feature is merged, add a description in a changelog for each release.
3. When we deem it's time for a release:
  1. Push the release to Pypi
  2. Push a new version of the docs (so that someone working with a specific version
  has the correct docs for that version).
  3. Push the release to a Github branch.

Any thoughts on this @papajohn @deculler @stefanv @henryem @rjboczar @alvinwan ?

**Comment by papajohn** [comment]
I think we probably have another semester of our current workflow before we
can behave like datascience is a stable software package.

**Comment by stefanv** [comment]
As you mention above, we typically  assocate different parts of the version number with different kinds of changes.  E.g., in a ``major.minor.revision`` system, it is quite typical to use ``revision`` for bug-fixes, ``minor`` for new releases, and ``major`` for API-breaking changes.  For young projects, such as this, API's are sometimes broken for ``minor`` versions, although the sooner you can settle on a stable API the better.  Also, it is very helpful to users to document *all* breaking API changes.

As for the docs, here is an example of how we host the different version for scikit-image (see sidebar):

http://scikit-image.org/docs/stable/

It is possible to have Travis-CI automatically build packages.  @matthew-brett has a lot of experience with all of this.

**Comment by papajohn** [comment]
Once we have a staff for next semester (probably next week), let's get
together and see what parts of the scikit-image model we can adopt without
too much overhead. The output looks great. Thanks for pushing on this
issue, Sam.

**Comment by SamLau95** [comment]
This is resolved in [release v0.4.0](https://github.com/data-8/datascience/releases/tag/v0.4.0) which put the docs on http://datascience.rtfd.org/ with versioning. Still some rough edges but this will let us move forward.
