### ISSUE TITLE
Methods that need more docs

### ISSUE THREAD

**Issue by SamLau95** [data-8/datascience#163]
Housekeeping for which methods still need docs (just in the order they appear in
the documentation, not by priority).

These methods have just a sentence or two in the docstring.

**Creation**
- [x] from_rows (adnanhemani edit: this method is now deprecated. No docs required.)
- [x] from_records
- [x] read_table
- [x] from_df
- [x] from_array

**Accessing Values**
- [x] num_rows
- [x] rows
- [x] column_labels
- [x] columns
- [x] column_index
- [x] first
- [x] last

**Mutation**
- [x] set_format
- [x] move_to_start
- [x] move_to_end
- [x] append
- [x] remove

**Transformation (I'd say these are the most used methods)**
- [x] copy
- [x] drop
- [x] where
- [x] sort
- [x] group
- [x] groups
- [x] stack
- [x] join
- [x] stats
- [x] move_column
- [x] pivot_bin (needs examples)

**Exporting/Displaying**
- [x] show
- [x] as_text
- [x] as_html
- [x] #520
- [x] to_df
- [x] to_array

**Visualizations**
- [x] plot
- [x] points

**Others**
- [x] Row class
- [x] Rows class

---

These methods have better docs (eg. an example or a description of the args) but
I'd still say they could use more documentation.
- [x] from_columns_dict
- [x] pivot
- [x] pivot_bin

**Comment by Brainz456** [comment]
Any of these still require updating?
I would be interesting in writing some up.

**Comment by adnanhemani** [comment]
@Brainz456 - yes these do. Please check the latest documentation at data8.org/datascience for the latest state/version of the documentation. If you do decide to work on this, please update the checklist above as well as you create PR(s) for these methods. Thanks!!

**Comment by erichamers** [comment]
Hey guys! Is anyone still working on this issue? I don't see any assignees, I'd be willing to jump in and help with this.

**Comment by adityakuppa26** [comment]
@SamLau95  @adnanhemani  Isn't column_labels deprecated? Do we still add docstrings for such?

**Comment by adityakuppa26** [comment]
#440

**Comment by adityakuppa26** [comment]
issue 163: added documentation for all accessing value methods #440

**Comment by adnanhemani** [comment]
@erichamers - we don't have any one person solely working on this issue. If you can, please fork our repo, and submit a PR! It'd be super appreciated!

@adityakuppa26 - I reviewed and merged #440. Thanks for this!! For `column_labels`, no need to make documentation for that - I'll mark it off on the list above.

**Comment by rajalakshmi139** [comment]
Hi
I would be interested in writing documents for some of the methods if they are still open.

**Comment by adnanhemani** [comment]
Hi @rajalakshmi139: yes, please check the methods above and send in a PR when you're ready. Thanks!

**Comment by davidwagner** [comment]
@rajalakshmi139, Agreed, would love to see PRs.  Ideally, break up your work into a few separate PRs, rather than one giant PR with all of the documentation.

**Comment by hmstepanek** [comment]
Remaining documentation that needs to be done from the original issue:

# Creation
- [ ] from_records
- [ ] read_table
- [ ] from_df
- [ ] from_array

# Mutation
- [ ] set_format
- [ ] move_to_start
- [ ] move_to_end
- [ ] append
- [ ] remove

# Transformation (I'd say these are the most used methods)
- [ ] stack
- [ ] pivot_bin (needs examples)

# Exporting/Displaying
- [ ] show
- [ ] as_text
- [ ] as_html
- [ ] index_by
- [ ] to_df
- [ ] to_array

# Others
- [ ] Row class
- [ ] Rows class

**Comment by aryan26roy** [comment]
Hey, I am new to Open Source and i would like to contribute to this.

**Comment by adnanhemani** [comment]
Hi @aryan26roy, please see any of the methods above that still need documenting and send in a PR when you're ready. See an example PR for this (like #456 or #457) for a good example.

**Comment by SambhaviPD** [comment]
Does any of these require updating? I am new to open source and would like to contribute.

**Comment by adnanhemani** [comment]
Hi @SambhaviPD - please see above comment.

**Comment by SambhaviPD** [comment]
Hi @adnanhemani , are you referring to #390 or #165 (the list mentioned by @hmstepanek ?

**Comment by vrii14** [comment]
Hi, I'm new to open source and would like to contribute in these docs. Is any of these open?

**Comment by krisstee** [comment]
I have an included a PR to contribute to this issue. Please let me know if any adjustments need to be made!

**Comment by adnanhemani** [comment]
@SambhaviPD, @vrii14: The documentation that still needs to get done is in https://github.com/data-8/datascience/issues/163#issuecomment-691587722

**Comment by CodTan** [comment]
issue 163: Updated documentation for all methods of creating a table; PR #467

**Comment by CodTan** [comment]
> Remaining documentation that needs to be done from the original issue (after PR #466 and #467):
> 
> ### Creation
> * [x]  from_records
> * [x]  read_table
> * [x]  from_df
> * [x]  from_array
> 
> ### Mutation
> * [x]  set_format
> * [x]  move_to_start
> * [x]  move_to_end
> * [x]  append
> * [x]  remove
> 
> ### Transformation (I'd say these are the most used methods)
> * [ ]  stack
> * [ ]  pivot_bin (needs examples)
> 
> ### Exporting/Displaying
> * [ ]  show
> * [ ]  as_text
> * [ ]  as_html
> * [ ]  index_by
> * [ ]  to_df
> * [x]  to_array
> 
> ### Others
> * [ ]  Row class
> * [ ]  Rows class

**Comment by vrii14** [comment]
@adnanhemani 
Could you please guide me to where exactly is the row and rows classes? I couldn't find it.

**Comment by adnanhemani** [comment]
@vrii14 : [Here](https://github.com/data-8/datascience/blob/master/datascience/tables.py#L5379-L5423)

**Comment by AdilGM** [comment]
Hey! Is there any more documentation that needs to be done that I could help out with?

**Comment by adnanhemani** [comment]
@AdilGM please check the list above - and if there's anything in the repo that's not listed here but doesn't have documentation, please feel free to send in a PR as well :)

**Comment by anshpujara14** [comment]
Hey anymore documentation required to be done? Willing to help!

**Comment by davidwagner** [comment]
@anshpujara14 Thank you for your offer -- see the list at the top of this issue for some ideas on further documentation!

**Comment by davidwagner** [comment]
@PubliusV,  If you take a look at the style we've used for other docs and follow them, that should get you most of the way.

**Comment by HarshKumarSingh07** [comment]
Hey everyone, @davidwagner @adnanhemani,  I have generated a pull request kindly verify once and please suggest improvements if required. I being a newbie to open source, any suggestions would be highly appreciated.

**Comment by Hetarth02** [comment]
I would like to help with documentation, can someone please guide me on the current stats of the docs and which topics need documentation?

**Comment by Shershon25** [comment]
Hey! If no one is currently adding documentation to the 'Rows' class, can I try adding to it?

**Comment by adnanhemani** [comment]
Hi @Shershon25 - we don’t have anyone working on this AFAIK. Please feel free to take any methods/classes and open a PR whenever your code is ready!

**Comment by Shershon25** [comment]
Thank you! I have opened a PR.

**Comment by adnanhemani** [comment]
I believe we've now concluded all of the above listed methods. I will run another audit through all the files and list any methods that require more documentation. Once I complete that, I'll close this issue and open new ones.

**Comment by adnanhemani** [comment]
This task is actually finished, I'm going to send in some updates for the misformatting of some methods. Thanks all for your help!!
