### ISSUE TITLE
Add test to install datascience in scipy-notebook's environment

### ISSUE THREAD

**Issue by SamLau95** [data-8/datascience#183]
From Ryan:

> Rebasing on our own single user container isn't difficult, and we'd benefit by not getting caught off guard when upstream changes things, but the trade-off is more maintenance when we do want to track upstream changes (e.g. going to the next version of jupyter). The alternative is to test datascience on scipy-notebook's environment. Can you add a build test to datascience that attempts to install in a scipy-notebook container?

**Comment by davidwagner** [comment]
Is this still relevant?  I don't quite understand what this is asking for so I'm not in a good position to evaluate it.

**Comment by SamLau95** [comment]
I don't quite remember either but this sounds like an issue for the JupyterHub infrastructure rather than the datascience package. I think we can safely close this issue.

**Comment by deculler** [comment]
It would be really valuable to reopen this question with them.  Chris put
in an issue years ago.  Amusing to see.  We should try again.  But there is
value in scipy independent of Jupiter.

**Comment by davidwagner** [comment]
OK.  I'll close this.  If someone understands this, I hope you'll file an issue at https://github.com/berkeley-dsep-infra/datahub/issues/new -- I don't understand this well enough to create an issue there myself.
