### ISSUE TITLE
Table.plot should take column_for_xticks as optional

### ISSUE THREAD

**Issue by deculler** [data-8/datascience#185]
If it is not specified, it should be assumed to be 0:Table.num_rows.  Otherwise it is much harder to do the obvious thing of just plotting the values in a table.  And it is unnecessarily different from matplotlib plot.

**Comment by cboettig** [comment]
:+1:  Likewise, if y values are listed explicitly, it would be nice if the `plot` method would plot only those y values and not other columns in the table.  Currently it is necessary to first subset the table, and then plot:

```py
tbl = Table([range(25), np.random.randn(25), np.random.randn(25), np.random.randn(25)], ["A", "B", "C", "D"])

# This plots A vs B, C, D, etc.., instead of A vs B.  That feels unexpected to me.  
tbl.plot("A", "B")

# meanwhile this feels redundant
tbl.select("A", "B").plot("A", "B")

```

As you probably know, `pandas` already has both the behavior David mentions and the behavior of plotting just the columns given in the `y` argument:

```py
## Plots just A vs B, 
tbl.to_df().plot("A", "B")

## Plots A vs B & C but not D
tbl.to_df().plot("A", ["B", "C"])

## Plots just B vs row number:
tbl.to_df().plot(y = "B")
```

**Comment by deculler** [comment]
plot fails if column_for_xticks is unspecified.  This isn't picked up by the tests, as we don't have test for much of the plotting functions.  We could add tests for execution completion, even if we don't look at the quality of the graph.  A fairly comprehensive test is in the TableDemos notebook https://github.com/deculler/TableDemos/blob/master/BerkeleySalary.ipynb.  I'll PR the fix so this can be closed.
