### ISSUE TITLE
Feature request: allow datascience.maps Circle.map_table to take column radius

### ISSUE THREAD

**Issue by pattyf** [data-8/datascience#188]
Current Maps.py code for Circle.map_table supports setting color for each point feature based on the value in the column 'color'. You can also set a single value for color for all features. It would be great if this same behavior worked for radius. That would allow for proportional and graduated symbol maps. I'm attaching a simple revision to maps.py and a notebook to demonstrate this functionality.
 

[maps_circle_radius.zip](https://github.com/data-8/datascience/files/110506/maps_circle_radius.zip)

**Comment by papajohn** [comment]
Great idea.

**Comment by papajohn** [comment]
Fixed in #214
