### ISSUE TITLE
Table.append should not accept arbitrary iterables

### ISSUE THREAD

**Issue by nishdesai** [data-8/datascience#204]
Currently, Table.append takes in an iterable that should represent a row in the table, and it maps elements of the iterable onto columns in the table to create a new row. This works well for lists or tuples, but if a string is passed in, the method puts a character of the string in each column. This can be confusing for students who don't understand this behavior. 

It would be better to check that the argument is an iterable of a type that makes sense to use as a row. Below are screenshots from a Piazza post about this issue.

![image](https://cloud.githubusercontent.com/assets/2476063/13207294/aef17324-d8c1-11e5-8945-895256237c43.png)
![image](https://cloud.githubusercontent.com/assets/2476063/13207295/aef4e130-d8c1-11e5-83d5-559a66918758.png)

**Comment by thesurfermac** [comment]
Will fixing the parameters for Table to be a list or tuple fix this?

**Comment by deculler** [comment]
No, there are many other iterables that make sense, including map and
range.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by adnanhemani** [comment]
Merged into master
