### ISSUE TITLE
Extend where method functionality

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#207]
Proposal: create a plain-language interface for filtering based on one column. E.g., assuming `x` is a label in `t`

```
t.where_column('x', equals(3))
t.where_column('x', between(-2, 2))
t.where_column('x', less_than(4))
t.where_column('x', not less_than(4))
t.where_column('x', less_than(4) or greater_than(6))
```

We could even let functions on the original column be arguments to the comparators.

```
t.where_column('x', equals(np.mean))
t.where_column('x', not equals(max))
```

Thoughts?

**Comment by SamLau95** [comment]
I actually think we could add this functionality to `where`, since it already supports statements like:

    t.where('x', 2)

We could add the ability to pass in a function as the second argument, which would look like your examples above.

I like this because it solves a common problem with chaining `where` calls:

    t.where(t['x'] != 2).where(t['y'] == 4) # doesn't work
    t.where('x', not_equals(2)).where('y', equals(4)) # works

**Comment by papajohn** [comment]
I like it. `t.where('x', between(2, -2))` would save a lot of typing.
