### ISSUE TITLE
Issues with line plots?

### ISSUE THREAD

**Issue by cboettig** [data-8/datascience#210]
PR #200 fixed a bug in plotting where the x-axis would be incorrectly labeled in examples like the one below.  It looks like this problem has now returned (and seems to show up in more cases than it used to?).  For example, in current (0.5.9 version)

```py
land_ice_src = "http://climate.nasa.gov/system/internal_resources/details/original/499_GRN_ANT_mass_changes.csv"
land_ice = Table.read_table(land_ice_src, skiprows=9)
land_ice.plot("TIME (year.decimal)")
```

Note this results with x-axis labels going up to 2003, even though the data are actually shown all the way up to 2015.

**Comment by papajohn** [comment]
Fixed in #214
