### ISSUE TITLE
Add a way to apply a function to each row of a table

### ISSUE THREAD

**Issue by henryem** [data-8/datascience#213]
In multivariate classification and regression, it's common to apply a predictor function to each row of a table.  The predictor function often just treats the row like a numerical vector.  `apply` currently expects a function that takes one argument for each column, not a function of a single array.  This means we currently have to jump through some hoops to do this.  Current options are:

1. Use a list comprehension on the rows of the table.  Since students in Data8 don't learn list comprehensions until late in the semester, this isn't viable.
2. Use a for loop over the rows.  This is inelegant and leads to verbose code that's hard to understand.
3. Use `Table().with_column("row", original_table.rows).apply(f, "row")`, which is cute but too magical.
4. Write functions with *args.  Students don't learn this.

Instead, the proposal is to add a Table method that does this directly.  It could be called `row_apply`.  It takes a single argument, a function from Row to anything.  `t.row_apply(f)` is equivalent to `np.array([f(row) for row in t.rows])`.

Two issues with this proposal:
1. It's worth considering whether the argument should instead be a function from NumPy array to anything.  In machine learning, the typical case is homogeneously-typed columns, and an array would be more natural.  Students may not understand the distinction between rows and arrays.
2. I'm also a little reluctant to add a new method to Table that's subtly different from an existing method (`apply`).  If anyone can think of a better solution, that would be great.

**Comment by cboettig** [comment]
Why not specify add an option to specify the axis for `apply`, as in pandas?  

I appreciate that the base types in `pandas` `DataFrame` objects add too much complexity for the level of the course and I think `Tables` does a great job in side-stepping all of those issues and providing us with a simpler data structure that fills the same fundamental role.  Still, from the perspective a connector instructor who is new to both `pandas` and `Tables` I think `Tables` would be much easier to teach and use in the course if it maintained a bit tighter parallelism between methods.  So often there are methods in `Tables` that are almost identical to those in `pandas` but use a different word to refer to the method, or a slightly different syntax.  Perhaps these things have been carefully considered and their are good pedagogical reasons for the differences, but in some places this hasn't been obvious.  My apologies for the rant!

**Comment by henryem** [comment]
Sorry, I should have been more clear about the problem.  The distinction isn't between applying over columns versus applying over rows, which is what the `axis` argument does in `DataFrame.apply`.  We still want to call a function once for each row in a table.  The question is: does the function you're applying have this signature:

`def predictor(feature0, feature1, feature2, feature3):`

...or this one:

`def predictor(features_array):`

Currently `Table.apply` expects the first kind of function (with one argument for each column you apply the function to), and there's no direct way to use the second kind of function.  But when you're doing something like linear regression where the input is really just an array of anonymous numbers, the first kind of function would be very bad style, since you'd have to rewrite it every time you changed the number of features you were using.

**Comment by cboettig** [comment]
@henryem sorry for my confusion.  Right, I see the point (I think) that you'd want to define a function that just takes the row as an argument, rather than naming each column; e.g. [borrowing this example](http://stackoverflow.com/a/13337376/258662)

```py
In [49]: df
Out[49]: 
          0         1
0  1.000000  0.000000
1 -0.494375  0.570994
2  1.000000  0.000000
3  1.876360 -0.229738
4  1.000000  0.000000
```

```py
In [50]: def f(x):    
   ....:  return x[0] + x[1]  
```  

```py
In [51]: df.apply(f, axis=1) #passes a Series object, row-wise
```

```
Out[51]: 
0    1.000000
1    0.076619
2    1.000000
3    1.646622
```

whereas the traditional behavior of `Table().apply` is more akin to something like `df["select_column"].apply(fn, axis = 0)` in pandas (hence my comment about axes).  It just feels like the syntax in the two modules is more different than it needs to be, which make common tasks like the one you've pointed out here harder or more awkward to do in Tables than it is in `pandas`.  I thought by lining up the syntax of two a little more, the Tables syntax would be both easier to learn and less likely to stumble over use cases that haven't been encountered.  Like you say, just tacking on a new method like `row_apply` when these things come up doesn't seem like the ideal way to build a nice user interface.  

Again apologies if I'm speaking past the issue at hand, and thanks for your patience in clarifying.

**Comment by henryem** [comment]
No, I really appreciate your comments.

Suppose you had a function with two arguments that aren't treated symmetrically and are even of different types.  Here's an example:

`def shared_key_encrypt(message, key):
  "Produces an encrypted version of a message that can be decoded with a certain numerical key."
  ...
  return encrypted_message
`

and you wanted to apply it to the rows of a DataFrame or Table that contained a column of messages ("message_column") and a column of encryption keys ("key_column").  I don't know of a nice way to do that in `pandas`.  Currently `t.apply(shared_key_encrypt, ["message_column", "key_column"])` will do it in `datascience`.  So `datascience` handles this use case better than `pandas`, but it handles the machine learning case (where your function takes an array as its single argument) worse.

It's true that we could switch `apply` to work like `pandas` `apply` (basically, to do what `row_apply` is proposed to do, except with optional selection of columns via the second argument).  That is, if we try to apply over multiple columns, we could package them up into a list and pass them as a single argument to the function being applied.  But I think there have been some nice applications for the current behavior of `apply` in teaching about higher-order functions.  And the `pandas` behavior is weird if the table has heterogeneous types.  Maybe @papajohn can comment.

**Comment by cboettig** [comment]
What about:

```
def f(row):
  shared_key_encrypt(row["message"], row["key"])

df.apply(f, axis = 1)
```

(could be done with an inline `lambda` but I find that pedagogically more confusing).  I think that's the same as how `Tables` apply works in your example, and not much less elegant.

I'm very inexperienced with `pandas` -- I'm an R user and only learn something in `pandas` when I cannot figure out how to get `Tables` to do what I want.  Still, it seems to be pretty battle-tested and there's almost always someone on stackoverflow with a clever `pandas` solution.  I realize `Tables` is still evolving, but I can't help feel we're not making the best use of the community knowledge in the design of some of the pandas syntax.  But my experience teaching this stuff to undergraduates is essentially negligible compared to @papajohn 's, so would defer to him.

**Comment by papajohn** [comment]
Leaving the `axis=...` part aside, I think there's a proposal to make `Table.apply(f)` apply `f` to whole rows, while `Table.apply(f, label)` applies `f` to the values in the column with some `label`. There's nothing wrong with that proposal — it just makes the signature of `f` a bit harder to predict, but would make it behave like pandas' `apply` and avoid any new method names.

**Comment by papajohn** [comment]
Added in #214
