### ISSUE TITLE
feature request: install numexpr for pandas query?

### ISSUE THREAD

**Issue by cboettig** [data-8/datascience#215]
@ryanlovett Would it be possible to get the `numexpr` module installed on the ds8 & data8 environments?

**Comment by ryanlovett** [comment]
Yes, I'm starting the ansible build process now on data8.

**Comment by ryanlovett** [comment]
Done. Let me know if it looks okay and I'll push to ds8 too.

**Comment by cboettig** [comment]
ah, works great, many thanks! do push to ds8 too.

**Comment by ryanlovett** [comment]
Updated on ds8 last week.
