### ISSUE TITLE
feature request: install urllib2 on data8 / ds8 servers?

### ISSUE THREAD

**Issue by cboettig** [data-8/datascience#216]
Can we get `urllib2` module installed?  I see we have `urllib` installed, but apparently I'm not the only one who found the `urllib` syntax needlessly complex...

**Comment by ryanlovett** [comment]
According to https://docs.python.org/2/library/urllib2.html, urllib2 doesn't exist in Python 3:

> Note The urllib2 module has been split across several modules in Python 3 named urllib.request and urllib.error. The 2to3 tool will automatically adapt imports when converting your sources to Python 3.

Have you thought about [requests](http://docs.python-requests.org/en/master/)? Its really nice IMO and it is already in the build. If you try it and don't care for it we can chat about alternatives. 

Also, I forgot to mention, could you file future issues like these against the [connector-instructors](https://github.com/data-8/connector-instructors) repo? The datascience repo is just for the python library.

**Comment by cboettig** [comment]
ah right, sorry about posting to the wrong repo.  thanks for point me to `requests`, that looks like it will do the job for me.
