### ISSUE TITLE
datascience clobbers the built-in 'all' function

### ISSUE THREAD

**Issue by henryem** [data-8/datascience#217]
datascience/predicates.py includes the line `all = ['are']`.  Unfortunately, this means that importing datascience into the global environment (which every class notebook does with `from datascience import *`) clobbers the built-in `all` function.  I'm not sure what the purpose of `all` is (I assume it makes something more fluent), so I can't suggest a fix.

**Comment by papajohn** [comment]
That's embarrassing. Fixed in 0.5.15, just pushed to pypi.
