### ISSUE TITLE
Add function to check out a project

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#218]
It would be great if installing `datascience` gave easy access to all of our materials. We could bundle our automatic git checkout functionality into a `datascience` function. Then, someone could start in a fresh environment with anaconda and git, run

`!pip install datascience`

then

`from datascience import *`
`checkout_project('data-8/data8assets`, `labs/lab01`)`

and they'd be off and running.... Thoughts?

**Comment by SamLau95** [comment]
Sounds cool! What use case did you imagine for this functionality?

**Comment by a-adhikari** [comment]
John, would this help faculty at other schools get access to our labs and
projects?
Ani

On Sat, Apr 2, 2016 at 2:39 PM, Sam Lau <notifications@github.com> wrote:

> Sounds cool! What use case did you imagine for this functionality?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/data-8/datascience/issues/218#issuecomment-204807873>
>



-- 
Ani Adhikari
Teaching Professor
Department of Statistics
University of California, Berkeley

**Comment by papajohn** [comment]
Anyone who doesn't have an account on our server can still work on our
projects without understanding how git works. Yes, this would facilitate
adoption of our materials.

**Comment by SamLau95** [comment]
Ah, makes sense. So I would run `checkout_project(...)` in a notebook / python REPL and afterward my folder structure would look like:

```
~/sams_stuff/
  data-8/
    data8assets/
      labs/
        lab01/
          lab01.ipynb
          <etc>
```

Is that what you had in mind?

**Comment by papajohn** [comment]
That's what I was thinking. Obviously this idea is not high priority, but
we should consider it as one way of distributing projects, since I think
hosting JupyterHub and our checkout server is a lot of overhead for many
instructors at other universities.

**Comment by a-adhikari** [comment]
This is a great idea, John.
Ani

On Sat, Apr 2, 2016 at 3:15 PM, John DeNero <notifications@github.com>
wrote:

> That's what I was thinking. Obviously this idea is not high priority, but
> we should consider it as one way of distributing projects, since I think
> hosting JupyterHub and our checkout server is a lot of overhead for many
> instructors at other universities.
>
> On Sat, Apr 2, 2016 at 3:13 PM, Sam Lau <notifications@github.com> wrote:
>
> > Ah, makes sense. So I would run checkout_project(...) in a notebook /
> > python REPL and afterward my folder structure would look like:
> >
> > ~/sams_stuff/
> > data-8/
> > data8assets/
> > labs/
> > lab01/
> > lab01.ipynb
> > <etc>
> >
> > Is that what you had in mind?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/data-8/datascience/issues/218#issuecomment-204811085
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/data-8/datascience/issues/218#issuecomment-204811215>
>



-- 
Ani Adhikari
Teaching Professor
Department of Statistics
University of California, Berkeley

**Comment by SamLau95** [comment]
I agree. @elaine84 and @ryanlovett would want to know about this.

**Comment by ryanlovett** [comment]
Couldn't this also obviate the interact service?

**Comment by papajohn** [comment]
Maybe — One challenge is that if you run checkout(...) from one notebook,
you then have to switch to the notebook you checked out using the Jupyter
file browser. That's clunky. It's also very convenient to have a link from
the website, rather than a procedure that involves creating a new notebook,
opening a library, and typing in some command. If we could clean up these
issues, then maybe we could have one unified interface for loading
materials. I'm open to ideas, but haven't figured out how to do that yet.

**Comment by elaine84** [comment]
This is interesting...! I'm trying to understand the user(s) we're thinking of.  The earlier comments by @papajohn seem to describe someone who can find a terminal and run `pip install` but doesn't understand basic git commands -- am I understanding this / does this make sense?  The later comments, starting with @ryanlovett 's observation that this could obviate the interact service, change the scope of use cases and users.  I do like that this could be used to get a local copy of materials in a GitHub repo (which is very different from the functionality of the `launch binder` tags -- @SamLau95 have you shown these to @papajohn and @a-adhikari ?) but it seems this could use some further hashing out.  How might this work?  (Would it require the user to have Git installed?)

**Comment by deculler** [comment]
we might want to have a 'basic' install, even of the whole package was the
default.  the datascience package is incredibly useful even separate from
the class.  I love the adoption kicker, but just wouldn't want people not
to use it because they felt encumbered by pulling in all the class
materials.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by elaine84** [comment]
Thanks @deculler for articulating that.  After thinking about it some more, I'd say that the `datascience` package for data analysis, etc., is a wonderful and general tool that should be kept distinct from course-specific materials (that depend on it).  I'm guessing that the default installation should just be the core package, and course-specific tools (interfaces to other materials on GitHub, etc.) could either be offered as a special `data8` installation, or via a separate package that depends on `datascience`.
