### ISSUE TITLE
Floats in where method can result in empty queries

### ISSUE THREAD

**Issue by jameswenzel** [data-8/datascience#222]
Imprecision in floats sometimes lead to empty table queries. Using `are.in_between` with small bounds results in an accurate query.
See https://github.com/jameswenzel/data-8-issues for the issue that my system had (not sure if it'll reproduce on others)

**Comment by papajohn** [comment]
Fixed by https://github.com/data-8/datascience/commit/ef59c17c6d057691cedfc6c31a00b5813dcd7f68
