### ISSUE TITLE
as_array returns an (n x 1) array

### ISSUE THREAD

**Issue by choldgraf** [data-8/datascience#226]
Currently using a table's `to_array` returns an array of shape `n x 1`. It seems more intuitive that this function would return an `n x n_columns` array instead (at least, this has confused several of the people I've been developing a course with). I think this would be an easy fix, but perhaps there's a reason that it's returning `n x 1` so I thought I'd ask before making a PR. Would people be open to a PR that would do something like this instead?

```python
# Determine output data type (object if multiple types)
dtypes = [c.dtype for c in xy.columns]
dt_out = np.object if len(set(dtypes)) != 1 else dtypes[0]

# Populate output array
arr = np.empty([xy.num_rows, xy.num_columns], dt_out)
for i, col in enumerate(xy.columns):
    arr[:, i] = col
return arr
```

**Comment by SamLau95** [comment]
This sounds fine to me.

In the textbook:

    grep to_array notebooks -r | wc -l
    0

In the `data8assets` repo:

    grep to_array . -r | wc -l
    0

Looks like we don't it in the foundations class.

**Comment by choldgraf** [comment]
oh? how do you get the data in a `Table` as a numpy array?

**Comment by SamLau95** [comment]
I think we typically do something like `table['latitude'][5]` to get the element at index 5 of the column `latitude` in the table. You can also do `table[4][5]` to get the element in column 4 (0-indexed), row 5.

**Comment by choldgraf** [comment]
So there's no way to just turn the whole thing into an array? (e.g., if we
want to pass the whole Table to a function that only accepts Numpy arrays)

**Comment by SamLau95** [comment]
Looks like there isn't; sounds like `to_array` should do that.

**Comment by choldgraf** [comment]
I see that there's a test in there is a test in there:

`test_array_roundtrip(table)`

that assumes that the output of `to_array` will be a structured array instead of an ndarray. So maybe somebody assumed that this is the desired behavior?

As far as getting the values of the data as an array, right now these are the (kind of hacky) options:

1. np.array(table.rows)
1. table.to_df().values

So it seems like these would be easy ways to do the array conversion. Perhaps `to_array` could have a `structured=False` parameter that would define whether to make it a structured array or as a simple ndarray?

WDYT?

**Comment by SamLau95** [comment]
I believe this is a function that @stefanv added about a year ago — maybe he has more input? It seems like this function is used infrequently enough (if at all) that I'm fine with either changing the output or adding a param.

**Comment by stefanv** [comment]
I guess the idea was that we wanted to preserve headers, and that various data-types could be used underneath the hood.  The way to generate a numpy array from that was to create a structured ndarray.

Would it make more sense to convert to an ndarray with a simple dtype, or to provide instructions in the docs on how to convert a structured array to a "standard" ndarray?

**Comment by choldgraf** [comment]
What about

```
    def to_array(self, structured=False):
        """Convert the table to a NumPy array.

        If all columns in `self` have the same data type, then the
        output array will have this datatype. If there is > 1 data type
        in `self`, then the output will be of dtype `object`.

        This will strip information about the column names, it only retains
        each column's data.
        """
        arr = np.array(self.rows)
        if structured is True:
            # Pull data types / names for structured array
            dtypes = [col.dtype.name for col in self.columns]
            names = self.labels

            # Populate output array
            labels = [(iname, idtype) for iname, idtype in zip(names, dtypes)]
            arr = np.array(arr, dtype=labels)

        return arr
```

**Comment by choldgraf** [comment]
Alternatively, since `values` is deprecated, we could un-deprecate it and change the behavior to be the same as a `DataFrame` (aka, it would return the ndarray of values). Then `to_array` would return a structured array.

**Comment by SamLau95** [comment]
`.values` sounds fine to me. Doesn't look like we use it in our assignments / textbook.
