### ISSUE TITLE
Add ways to manipulate strings without square-bracket indexing

### ISSUE THREAD

**Issue by henryem** [data-8/datascience#235]
In Data8 we're trying to avoid square-bracket indexing because it confuses some students.  This makes working with strings a little challenging.  Technically, a lot can be done with the workflow `string -> list -> table -> manipulate -> list -> string`, but that's pretty ugly.  I'd like to add a few functions to `datascience` to work around this.

Concretely, here are two things I'd like to be able to do.  (Ani says some connector instructors are interested in the first one, too.)
1. Index a subrange of a string.  This could be done like `Table.take` (e.g. `item_range("foobar", np.arange(1, 5))`) or like range indexing (e.g. `item_range("foobar", 1, 5)`).  This would have the added benefit of working on NumPy arrays.
2. Have a version of the `split` method that returns an array instead of a list.  Otherwise we have to wrap calls to `split` in `np.array`, which is confusing when students have only a vague idea about the difference between lists and arrays.  Since we can't teach regular expressions, `split` is a fairly core text manipulation tool.

I realize this is not really in-scope for the `datascience` library.  Other options include avoiding text manipulation; making another library for Data8-specific helper functions; or teaching lists and square-bracket indexing.  I don't really like any of those, but I'm open to other suggestions.

**Comment by henryem** [comment]
@papajohn

**Comment by papajohn** [comment]
What about `string -> array -> manipulate -> string`? Make an array of characters with `np.array` and then join it back up into a string?

**Comment by henryem** [comment]
Right, but we don't have a way to do slice indexing of arrays right now, either, without square brackets.

**Comment by papajohn** [comment]
Sure you do: http://docs.scipy.org/doc/numpy/reference/generated/numpy.take.html

`np.take(some_array, np.arange(start, finish))`
