### ISSUE TITLE
Bar chart from categories

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#242]
From @a-adhikari : `barh` should surely take a column of categorical data and draw the bar graph, without us having to do the grouping for it first. That would be consistent with hist having a default behavior when we don't specify bins.

**Comment by papajohn** [comment]
We should resolve #233 first.

**Comment by papajohn** [comment]
I think we'll need a new method for this behavior, since `barh` on one argument already has a useful behavior that's consistent with `scatter` and `plot`. 

Matlab calls the function that displays a categorical distribution a "histogram"

https://www.mathworks.com/help/matlab/matlab_prog/plot-categorical-data.html?requestedDomain=www.mathworks.com

**Comment by henryem** [comment]
@papajohn I'd like to have this for Data 8R this summer, and I'd be happy to implement it.

Is there a reason to resolve #233 first?  Presumably we'll need to preserve the public API for the many existing plotting methods anyway, and this is a common enough use case that I think it's worth supporting.

I think it's too confusing to call this a histogram, but I can't think of a clever name.  Perhaps `group_barh` (and `group_bar`)?  Another option is to make this the behavior of `t.barh(category_column='foo')`.  If either of those seems okay, I'll implement it.

**Comment by papajohn** [comment]
You can add it without #233 . `group_bar` is fine.

**Comment by henryem** [comment]
Closed by #293 in 0.10.0.
