### ISSUE TITLE
More flexible interact links

### ISSUE THREAD

**Issue by choldgraf** [data-8/datascience#248]
Hey folks - I wonder if there are plans to expand the functionality of interact links at all. In particular, these are two points that I think would be really useful in scaling the data8 infrastructure to a wider audience:

* Allowing interact links to work with non-data8 repositories
* Allowing interact links to work with private repositories

The second in particular would be useful, as it means that instructors could post answers via interact links without making their repositories available (and clonable) to students

**Comment by choldgraf** [comment]
(ps, let me know if this isn't the proper repo for this point...not sure how intertwined data8 / datascience are)

**Comment by choldgraf** [comment]
also pinging @cboettig in case he's thought about this at all...I seem to remember him mentioning this a few months back

**Comment by ryanlovett** [comment]
Hi Chris, the DS8-Interact repo is the best place to file these issues. This one is relevant: https://github.com/data-8/DS8-Interact/issues/18

I just opened https://github.com/data-8/DS8-Interact/issues/20.

**Comment by anthonysuen** [comment]
Hey Chris,

We have a small team looking into these issues. Sam has recommended that we turn the Interact Service into Nbextensions because that the server is the main bottleneck.  

Anthony
