### ISSUE TITLE
.Join method  is prone to putting the wrong things into a column.

### ISSUE THREAD

**Issue by anthonysuen** [data-8/datascience#249]
We ran across a problem in class today which I have abstracted into the attached .tgz file

The pdf shows what you get if you open the anomaly.tgz file and run the WTF_table_join_anomaly.ipynb file.

It is not unlikely that I'm just not getting it, but it looks to as though  the .join method 
is prone to putting the wrong things into a column.

Please forward  if appropriate.

Thanks.

**Comment by papajohn** [comment]
I haven't noticed a wrong join recently, and join was updated, so closing for now.
