### ISSUE TITLE
Make a Table a subclass of a pd.DataFrame

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#285]
Let's keep the interface, but use it as an extension to the Pandas dataframe interface instead of a replacement.

**Comment by papajohn** [comment]
FYI @SamLau95

**Comment by papajohn** [comment]
At this point, I think we'd only make this change if we transitioned `datascience` into an interface with multiple backends, like Keras.

**Comment by davidwagner** [comment]
Looks to me like we should close this as won't-fix. Objections?

**Comment by deculler** [comment]
Agree

**Comment by adnanhemani** [comment]
Agreed. I'll mark it.
