### ISSUE TITLE
Inconsistent legends and argument names for grouped graphs

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#303]
Both args should be called `group` and both legends should have the histogram style.

`scores.scatter('Midterm 1', 'Midterm 2', colors='Mentored')`

![download-1](https://user-images.githubusercontent.com/320145/33358033-f36bb896-d47a-11e7-9840-83687b019549.png)

`scores.hist('Midterm 1', group='Mentored', bins=np.arange(0, 41, 5), normed=False)`

![download-2](https://user-images.githubusercontent.com/320145/33358040-fd0d3a28-d47a-11e7-9765-27ed082dddbf.png)

**Comment by adnanhemani** [comment]
Closed per #384.
