### ISSUE TITLE
Ambiguous truth value in .append()

### ISSUE THREAD

**Issue by mjr225** [data-8/datascience#307]
Error throws when trying to append a row to an existing table using ".append()"

![screen shot 2018-01-02 at 11 40 37 am](https://user-images.githubusercontent.com/7960723/34497382-38e8e4a0-efb2-11e7-82f4-e344f17db33c.png)

**Comment by adnanhemani** [comment]
According to the error message, it seems that trials isn't an table. It looks like an array - are you sure it's a table?

**Comment by mjr225** [comment]
No, in this case it is an array.

The source code in `append` has other functionality for handling an array being appended, but it does not get past this first conditional because of the ambiguous truth value.

**Comment by adnanhemani** [comment]
A row is not a NumPy array - which is what's causing your error. You must make the data you're trying to append to a Python list.

**Comment by adnanhemani** [comment]
It might be a feature/bug fix to get around this issue - thoughts @papajohn ?

**Comment by papajohn** [comment]
It does seem like it should be possible to append an array that represents a row. If we can fix the code to allow that, I approve.

**Comment by adnanhemani** [comment]
Ok going to start making that change now

**Comment by adnanhemani** [comment]
Made the change needed in PR #309.

**Comment by adnanhemani** [comment]
Marking as resolved.
