### ISSUE TITLE
Histograms have error terms in labels

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#311]
<img width="668" alt="screen shot 2018-03-07 at 2 16 01 pm" src="https://user-images.githubusercontent.com/320145/38580072-dad55f34-3cbd-11e8-9cbf-6515e88fa0e7.png">

Numpy v1.14.x (released Jan 6) changed the algorithm (look for the section titled "Many changes to array printing") for the string representation of floating point numbers.  If you add this line of code, it changes back to the 1.13.x algorithm, and the histogram x-axis labels are sane (i.e., don't contain the small error terms):

`np.set_printoptions(legacy='1.13')`

**Comment by adnanhemani** [comment]
Marking as dupe to #347. Copying this information over to that thread.
