### ISSUE TITLE
Minor HTML error in Table() tbody

### ISSUE THREAD

**Issue by deltafactory** [data-8/datascience#312]
In the `as_html` method, the <tbody> tag is started just after the column headings but the `</tbody>` is closed as part of every row here:
https://github.com/data-8/datascience/blob/master/datascience/tables.py#L1864

This has a minor side-effect of creating 2 `<tbody>` regions (in Firefox - browser DOM fixes may vary) which causes the selector `.rendered_html tbody tr:nth-child(2n+1)` to match for 2 consecutive rows.

I think the fix would be to close `</tbody>` by append it just above the closing `</table>` tag.

**Comment by adnanhemani** [comment]
@deltafactory can you please verify that this problem is still occurring and if so, steps for replication. Thanks!

**Comment by deltafactory** [comment]
I had been using this as part of an online course over a year ago and no longer have access. Sorry, I won't be able to verify. If the mentioned table tags are properly paired in the output HTML all should be well. :)

**Comment by adnanhemani** [comment]
Oh, sorry for getting to this so late :(

On my testing in Chrome and Safari, I'm not seeing this bug so I'm not sure where this is occurring but I'll mark this issue as can't reproduce for now and if someone else stumbles upon this issue, I can take a look at it then!

Thanks again for trying to help us out though!

**Comment by adnanhemani** [comment]
It was fixed by #315!
