### ISSUE TITLE
Please update http://data8.org/ to v0.10.4

### ISSUE THREAD

**Issue by joemerante** [data-8/datascience#319]
Hi,

I realize the documentation on [http://data8.org/datascience/index.html](http://data8.org/datascience/index.html) and maintenance of the repo might be entirely separate, but there was no contact link there, so hopefully this message finds the maintainers of the site.

[http://data8.org/datascience/index.html](http://data8.org/datascience/index.html) currently has version 0.10.0 of this module, and it looks like 0.10.4 is the latest, which adds the `sample_proportions` function recently demonstrated in [https://www.edx.org/course/foundations-data-science-inferential-uc-berkeleyx-data8-2x](https://www.edx.org/course/foundations-data-science-inferential-uc-berkeleyx-data8-2x)

I cloned this repo and ran `make html`, and updated docs for 0.10.4 were generated correctly. Hopefully the site can be updated with them!

Thanks

**Comment by davidwagner** [comment]
Done.  Thank you for the report!
