### ISSUE TITLE
Make ec='w' default in histograms

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#320]

**Comment by adnanhemani** [comment]
@papajohn @a-adhikari - can someone please clarify what this would do? As per what I've read, this would turn the edgecolors of each bin to white. But as of what I can see when I make a histogram, this is already happening (picture attached below)

Is this issue outdated?

<img width="1142" alt="Screen Shot 2019-06-18 at 11 21 00 AM" src="https://user-images.githubusercontent.com/10746770/59657782-29572680-91bb-11e9-9c1f-15b7e2b331f6.png">

**Comment by papajohn** [comment]
I think this issue has already been fixed.
