### ISSUE TITLE
Cut a new release on pip?

### ISSUE THREAD

**Issue by choldgraf** [data-8/datascience#321]
Hey @SamLau95 - do you know when is the next planned pip release for the package?

**Comment by SamLau95** [comment]
We don't really have a schedule for making releases; typically we release whenever we need to update datahub. I can make a release if you'd like something out!

**Comment by choldgraf** [comment]
mostly it's just that some people were trying out the jekyll build thing, and the `pip` installable package still has the tables output bug in it, which is confusing some folks

**Comment by SamLau95** [comment]
Sorry about the long delay; just released version 0.10.5!
