### ISSUE TITLE
Table.take should accept a variable number of arguments

### ISSUE THREAD

**Issue by rameshvs** [data-8/datascience#332]
Stacking parentheses and brackets is confusing for beginners (e.g., `make_array(1, 2, 3)` is easier to understand than`np.array([1, 2, 3])`). Taking multiple rows with `Table.take` should also accept this syntax, so that all of the following work and produce the same results:
```
t.take(np.arange(3))
t.take[:3]
t.take([0, 1, 2, 3])
t.take(0, 1, 2, 3)
```

**Comment by papajohn** [comment]
Great. I'm skeptical of `t.take[:3]`, but I agree that the rest should work.

**Comment by rameshvs** [comment]
Agreed that `t.take[:3]` is a bit weird, but it already works, and is in the docstring for `_RowTaker.__getitem__` (and has been [for a while](https://github.com/data-8/datascience/pull/247)).
