### ISSUE TITLE
Why does `Table.append` mutate the table?

### ISSUE THREAD

**Issue by rameshvs** [data-8/datascience#334]
All the other operations that students learn (with the exception of the cosmetic `set_format`) are functional, and don't mutate tables or arrays. This includes `np.append`, which unfortunately has a similar name.

Why mutate the table instead of returning a new one? 

### Pros of mutating:
1. Performance: It's a little less memory efficient and probably a little slower to create a new table each time. This could be an issue on the memory-constrained jupyterhub environment?
2. Gets them primed to understand the behavior of `list.append`, and introduces students to mutation generally.

### Cons of mutating:
1. Thinking about state makes things more complicated; purely functional operators are inherently simpler to understand and explain, and don't get in the way of explaining the underlying concepts (simulation, table manipulation, etc.)

In my mind, it seems like the pedagogical win of being purely functional outweighs the pros, but I also could see how the pros (especially my item 1 above) might be pretty impactful.

**Comment by papajohn** [comment]
We tried to support both: append adds a row and with_row makes a new
table.  The naming goal was to be consistent with list.append. It would be
fine not to teach it in Data 8, I think.

**Comment by rameshvs** [comment]
Closing this, since the resolution is to only teach `with_row` in class.
