### ISSUE TITLE
X-axis labels truncated in some cases

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#338]
In some cases the x-axis label seems to be truncated.  For example:

```
t = Table().with_columns(
    'Value', make_array(2, 3, 9),
    'Proportion', make_array(0.25, 0.5, 0.25)
)

t.hist(bin_column='Value', bins=np.arange(1.5, 9.6, 1))
```

I don't understand what is causing this.

I have only been able to replicate this with examples that use `bin_column=` (or `count=`), but not with examples that don't.  I don't know if that's fundamental or an accident.

**Comment by adnanhemani** [comment]
Closed by #382.
