### ISSUE TITLE
Add a `shuffle` method to Tables

### ISSUE THREAD

**Issue by rameshvs** [data-8/datascience#340]
For doing permutation tests, `.shuffle()` is more intuitive than `sample(with_replacement=False)`.

Tables should have a shuffle method that returns a new table with all the rows in random order (i.e., does not modify the table).

**Comment by papajohn** [comment]
Sounds good to me.

**Comment by adnanhemani** [comment]
PR with these changes made #341.

**Comment by adnanhemani** [comment]
Marking as resolved.
