### ISSUE TITLE
Fix histograms not showing outlines for each bar

### ISSUE THREAD

**Issue by scottjlee** [data-8/datascience#343]
Examples on this page: https://www.inferentialthinking.com/chapters/07/2/Visualizing_Numerical_Distributions#a-histogram

**Comment by adnanhemani** [comment]
@scottjlee it seems to me that the outlines are now showing? I think this has to do with the ec='w' default issue - I'm marking this as a dupe to #320. Feel free to comment back with more specifics of the problem (what exactly we should be looking for on the histogram that's not that) and if this isn't the same issue as #320.
