### ISSUE TITLE
Color argument does not work for scatter plot

### ISSUE THREAD

**Issue by FelixNeutatz** [data-8/datascience#350]
Dear all,

I was trying to use another color scheme for the scatter plot. Unfortunately, it does not work as expected:
![image](https://user-images.githubusercontent.com/5217389/58787415-0f79e900-85ea-11e9-96d3-4d01dea0305e.png)

Did I do something wrong or is this a bug?

Best regards,
Felix

**Comment by adnanhemani** [comment]
Hi Felix, unfortunately that's not how the 'colors' argument is meant to work. 'colors' should be the name of a column in your table that is a categorical grouping of your data points - but it does not actually guarantee you a particular color for that category.

For example, if you look at the graphs in #303, you'll see in the scatter plot that the "mentored" column is a column of True/False and it basically separates out the categories of the data and plots each category with a different color. As also stated in #303, I'll be making the changes shortly as - you have just discovered - that the argument name and documentation isn't very clear as to the usage. Sorry about that!

Although we don't officially support custom colors, you can pass them in as vargs into the scatter function and they should work! (I just tried and verified.) The colors need to be in a formatted in a way supported by matplotlib as shown in this function (https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.scatter.html, look at the 'c' argument).

For example, I did this:
<img width="857" alt="Screen Shot 2019-06-18 at 4 39 13 PM" src="https://user-images.githubusercontent.com/10746770/59679191-9da7bf00-91e7-11e9-81ac-ef4f067db86a.png">

Hope this helps!

**Comment by FelixNeutatz** [comment]
Thanks for your response :)
