### ISSUE TITLE
.hist() now gives 'AttributeError: Unknown property density' error

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#351]
The following code used to work:

```
united = Table.read_table('http://inferentialthinking.com/data/united_summer2015.csv')
united.hist('Delay')
```

Now it gives a backtrace with the error "AttributeError: Unknown property density".  I don't know if something changed, or if there is some error on my end.  If something changed, how do we transition old notebooks to whatever is the new syntax?  Should there be some documentation to explain how to do this?

I ran into this with lec01.ipynb in http://datahub.berkeley.edu/user-redirect/interact?repo=summer&branch=gh-pages&path=su19/lecs/ (from https://github.com/data-8/summer/blob/gh-pages/su19/lecs/lec01.ipyn).

**Comment by adnanhemani** [comment]
From what I can read, it might be a Python2 vs Python3 issue? Did we recently upgrade to Python3 on datahub? Because it's Python3 now but I thought it was Python2 before?

**Comment by davidwagner** [comment]
We have some suspicions that it might be related to changes to configuration on datahub.  Looking at the history of changes to the requirements.txt file, though, I don't see anything obvious that jumps out at me (https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/image/requirements.txt).

We also have some suspicions that it might be related to the version of the datascience package (maybe v0.10.5 vs v0.10.6?).

Haven't tested either of these yet.

**Comment by davidwagner** [comment]
Here's what I'm thinking about steps to investigate these hypotheses:

1. Install a Python venv with requirements.txt taken from the current data hub deploy (see above) and see if we can locally confirm the problem.

2. Take the same venv, except modified to use an earlier version of the datascience package.  If that fixes it, then we can bisect to find the change that is relevant.

3. If it doesn't, then we can try using a venv that corresponds to an earlier version of the deploy on data hub from a month ago (say), and see if that fixes it.

These errors seem to be new; I suspect they weren't happening a month ago (because they probably would have popped up for Spring 2019 students).  I also think I tested these notebooks last week and didn't notice problems, but I couldn't swear to that (it's possible I might have overlooked the .hist errors).  Both of these make me suspect it might be related to some recent change to the Jupiter data hub configuration.

**Comment by davidwagner** [comment]
I have the impression we've been on Python 3 for a long time, so I don't quite see how it would be a Python 2 vs Python 3 issue, unless my memory is fooling me.

**Comment by deculler** [comment]
Tables has always been python3 exclusively.  Several of the ci issues arose
around 3.6 when default number printing changed to include commas.  The
doctest needs to compare values not the representation.  The read table
warning is due to pandas update.

**Comment by adnanhemani** [comment]
After doing some preliminary digging, it seems that upgrading matplotlib to v3.0.2 solves the issue...perhaps the latest deployment of datahub downgraded the matplotlib version?

**Comment by adnanhemani** [comment]
After doing some more digging, here's what I've finally come up with:

Starting matplotlib v2.2.0, the "normed" keyword has been deprecated and was thus changed to "density". AFAIK, change [v0.10.6](https://github.com/data-8/datascience/commit/fdb2fb4a22a92a2fe91d35b0d07905508053886b) in this library was made to accomodate this change in the matplotlib library (@rameshvs can you please confirm this?)

However, looking at the datahub deployment, the matplotlib versioning is v2.0.0 (before the "density" vs "normed" change) and might be the reason why we're seeing issues currently. A quick matplotlib upgrade to v3.0.2 removes all errors/issues on Table#hist.

While this all makes sense to me, the one key part of this theory that remains unexplained is: (given that the matplotlib version hasn't changed as part of the server [configuration file](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/image/requirements.txt) ever), how were we using a Matplotlib version >v2.2.0? (Which would allow us to not cause this error...)

**Comment by davidwagner** [comment]
Thanks for this!  I will test and see if I can confirm.

We've been on `datascience==0.10.6` since [Sept 10, 2018](https://github.com/berkeley-dsep-infra/datahub/commit/aa1c94c9adca963f5fff2d82d11674c435b053b8) and `matplotlib==2.0.0` for years (see the [blame report](https://github.com/berkeley-dsep-infra/datahub/blame/staging/deployments/datahub/image/requirements.txt)), so I a bit puzzled what caused this problem to pop up now and not before.

**Comment by ericvd-ucb** [comment]
thanks @adnanhemani for looking at this ( we looked at it together as well as the history for requirements.txt in github and the circleci history http://circleci.com/gh/berkeley-dsep-infra/datahub/) and we couldnt quite figure out where the hub image was changed in a way to introduce these errors.

**Comment by davidwagner** [comment]
I confirmed that updating to `matplotlib==3.1.0` fixes this bug.  I propose that we update to matplotlib 3.1.0 (rather than 3.0.2), as it is the latest stable version.  In particular, I propose that we push this config change to staging and then test it on other lecture notebooks to see if this breaks anything else.

**Comment by deculler** [comment]
I'm ok with that. Will this be reflected in requirements.txt?

**Comment by davidwagner** [comment]
@deculler, John suggests we should not list all dependencies in requirements.txt: see https://github.com/data-8/datascience/pull/301#issuecomment-380928606.  So, going by that, no, I don't think we'll put it in requirements.txt in this repo.  Instead, we'll update the datahub configuration that students use.

**Comment by deculler** [comment]
Perhaps we could provide some clear instructions in the readme or a
supplementary install so people don't have to rediscover what's needed to
be able to run our most basic notebooks.

I would love to be independent of pandas and jupyter if one we're not
actually using those capabilities.

**Comment by adnanhemani** [comment]
@davidwagner I like this idea. We can put it in the README near the top. How does that sound?

**Comment by davidwagner** [comment]
Sounds good to me.  We have an installation section but it doesn't really explain what's needed to install, so I think this would be helpful.  I think the requirements are ipython, matplotlib, numpy, pandas, scipy.  We could probably change the `pip install datascience` to `pip install datascience ipython matplotlib numpy pandas scipy`.

**Comment by adnanhemani** [comment]
The big issue is that matplotlib must be v0.3.0+...how do we want to list this down in the README? I think the bigger issue is that we need to make sure that users are aware about the version rather than just knowing that matplotlib is required in this case

**Comment by davidwagner** [comment]
How about `matplotlib>=3.0.0` instead of `matplotlib` in the `pip install` command line?  We could also add a comment below the command line noting that matplotlib version 3.0 or later is required.

**Comment by davidwagner** [comment]
I created a new issue for updating the README: #364 .  With that, I think that takes care of this issue.
