### ISSUE TITLE
Check readthedocs.org integration

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#360]
Github services are now deprecated (https://developer.github.com/changes/2018-04-25-github-services-deprecation/) and as of Jan 1 2019, they're now all disabled.  We were previously using Github services for integration with readthedocs.org (https://github.com/data-8/datascience/settings/hooks/6600680), but it appears that has now been automatically disabled.

Do we need to update our readthedocs integration, given this?  Maybe we need to add a webhook on Github?  (possibly relevant: https://docs.readthedocs.io/en/stable/connected-accounts.html)  Need to investigate whether we need to do anything...

I don't have admin/maintainer access to the project on readthedocs.org, so I can't check how it's configured over there or update the configuration.  We'll probably need to ask @SamLau95 for help giving us admin access over on readthedocs.org.  (It also has the wrong home page listed on readthedocs.org.)

**Comment by SamLau95** [comment]
I added `davidwagner` to the admin list for readthedocs — let me know if that username isn't right.

The docs are supposed to be regenerated each time Travis runs a build by running the `bash tools/deploy_docs.sh` command. This command pushes the docs to the `gh-pages` branch of this repo, which should update readthedocs in theory. However, this command isn't working at the moment because of an authentication issue (https://travis-ci.org/data-8/datascience/builds/543977273#L2404-L2510). It's possible that if we fix that command we'll also get the docs updating.

**Comment by adnanhemani** [comment]
@SamLau95 I locally triggered an upload to the gh-pages branch and no build was triggered on readthedocs. Could this perhaps mean that the GitHub integration with that branch is gone for good and we should try a new integration with webhooks now?

Also, @davidwagner did you trigger the latest rtd build (5 days ago)? If so, how did you do it - manually through the admin settings on rtd?

**Comment by davidwagner** [comment]
I can't remember.

Maybe it was triggered when my account was added as an admin to rtd?

Looking through the rtd web pages, I can't find any place to manually trigger a build.  I don't think I manually ran `make deploy_docs`, as the only change I see in the past few weeks is a push from you yesterday, which postdates that rtd build (see https://github.com/data-8/datascience/commits/gh-pages).

It appears that the documented way to trigger builds is through [webhooks configured at Github](https://docs.readthedocs.io/en/stable/webhooks.html).  It looks like on Github we have an integration with ReadTheDocs [set up via Github Services](https://github.com/data-8/datascience/settings/installations), but I remember that Github Services was deprecated earlier last year and supposedly turned off the start of this year, so that integration might no longer be working.  I suspect we might need to set up an integration via a webhook to get readthedoc to automatically trigger builds on each push.

**Comment by davidwagner** [comment]
Oh!   I think I did manually trigger a build on rtd.  There's a button to do it on https://readthedocs.org/projects/datascience/.  So that's probably why there was a successful build there.

**Comment by davidwagner** [comment]
I tried adding a webhook on Github, as instructed on the support pages at rtd.  Next time we push to master, let's check if it triggers a build on rtd.

**Comment by adnanhemani** [comment]
Ahh, I see. I probably don't see the button since I'm not a maintainer on there. I'll keep my eyes peeled for the next merge to master

**Comment by davidwagner** [comment]
OK.  I pushed to master, and it indeed triggered a build on rtd (https://readthedocs.org/projects/datascience/builds/), and now.  So it looks like the new webhooks are working and that was the fix, and now the updated docs are showing up on rtd.  I'll close this now.
