### ISSUE TITLE
README should list all dependencies

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#364]
The README should describe what else you need to install to use the `datascience` library.  In particular, we should probably change `pip install datascience` to `pip install datascience ipython matplotlib>=3.0.0 numpy pandas scipy` and add a comment below the command line noting that matplotlib version 3.0 or later is required.

**Comment by adnanhemani** [comment]
I'm marking this issue blocked on #335. If we can mark the requirements in requirements.txt and have them installed via pip through there, then there's no need for this issue.

**Comment by adnanhemani** [comment]
Closed as per #335
