### ISSUE TITLE
Should we warn every time, or only the first time?

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#370]
We generate a warning when passing an array or list to an `are.*` predicate, by raising a UserWarning.  (See PR #292 and issue #287.)

Currently, this means we will warn only once, the first time the programmer makes that mistake.  Subsequent instances of this mistake will not raise any warnings.  That's how UserWarnings work by default in Python.

Is this desirable?  Or is it better to warn every time?  If a student makes this mistake in their notebook, and changes something else in the notebook and re-runs that cell, no warning will be displayed the second time, even if their code still has the same mistake.  Is this desirable?  Perhaps we could make a case for either, but let's make sure we're choosing deliberately.

**Comment by davidwagner** [comment]
@papajohn, @a-adhikari, @adnanhemani, do you have any opinions on this?

**Comment by adnanhemani** [comment]
In this case, I think it might be preferable to warn every time. Only showing a warning to students once might not be helpful for repeat offenders of misuse of the API provided. Definitely would like to hear other opinions on this one - I could see consistent warnings freaking students out too.

**Comment by deculler** [comment]
Students aren't the only use case for tables.  Increasingly it is used in
code that lives on beyond the weeks lab.  "First time" is confusing, as you
observe.  If it is highly unlikely that the particular usage could be what
we intended - issue warning.  Provide a kwarg to suppress it.
