### ISSUE TITLE
deploy_docs.sh is failing on Travis because of xvfb

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#374]
In the most recent Travis builds (https://travis-ci.org/data-8/datascience), deploy_docs.sh is failing:

```
$ bash tools/deploy_docs.sh
Can't open /etc/init.d/xvfb
```

Per https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui, it appears changes are needed to make this work with Ubuntu 16.04 xenial, which Travis recently moved to.

(Possibly relevant: https://benlimmer.com/2019/01/14/travis-ci-xvfb/, https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment, https://stackoverflow.com/q/35403127/)

In the meantime the workaround is to manually `make deploy_docs`.

**Comment by adnanhemani** [comment]
I tried to fix it with #376, but unsure if it did the trick. It got past this error that we see here, but still stuck on the authentication problems mentioned in #363. Please do not merge #376, as I've made some bad changes required to trigger Travis to build the docs even when it shouldn't - I'll make a new PR with the right changes later when we can figure out exactly how to fix the docs.

**Comment by davidwagner** [comment]
#376 looks like that fixed the xvfb problem: it got past the point where it was failing before (the xvfb part succeeded), and now failed only at the very last step where it tries to upload to Github.  So, yes, it looks like that was indeed the correct fix for the xvfb problem.

**Comment by davidwagner** [comment]
To clarify my prior comment: this isn't fixed yet; PR #376 shows that changing the `.travis.yml` in the way shown in PR #376 will fix the xvfb problem; but PR #376 isn't mergeable; now we need to create a mergeable PR that contains that same fix.  Your test is PR #376 does demonstrate how to fix it.

**Comment by adnanhemani** [comment]
Closed by #379
