### ISSUE TITLE
Write tutorial for the Maps module.

### ISSUE THREAD

**Issue by adnanhemani** [data-8/datascience#390]
Currently, it says "To come" - we need to put examples of our library in there.

**Comment by loukikstudent** [comment]
Hi!
I am currently a student and trying to contribute as much as i can, i would like to help you out in this issue, can you guide to the right direction.
Thank you

**Comment by adnanhemani** [comment]
Hi @loukikstudent, I wouldn't recommend this ticket for someone who hasn't used our Maps module (or our library) at all. Please see #163 for a better ticket to start on.

**Comment by Prad06** [comment]
Hi @adnanhemani, I am an undergrad, totally new to open source, is there anything that I can help with, it would be great if I can help in any way.
Thanks!

**Comment by adnanhemani** [comment]
@Prad06 - please see above comment.
