### ISSUE TITLE
Change all Circle arguments for 'radius' to 'area'

### ISSUE THREAD

**Issue by adnanhemani** [data-8/datascience#407]
This is to be consistent with how we've been drawing circles everywhere else around the Maps module

**Comment by papajohn** [comment]
To represent a magnitude, area is more appropriate than length based on
visualization principles. I think we therefore need to live with the
inconsistency or change everything else to area.

**Comment by adnanhemani** [comment]
The other place where this is partly used is in the `radius` argument of `Circle`. I do think that we need to be consistent across this because it makes no sense to have to instantiate a Circle using a radius parameter - while having to pass in the area of the circle as a column to the table when trying to recreate the same Circle using the `map` method.

So just to confirm, you think it would be better to change the Circle to only have an area property that can be changed rather than radius if we want to make everything consistent? Thanks for chiming in on this! :)

**Comment by papajohn** [comment]
Yeah, areas everywhere is the best way to be consistent. Radius-based sizes
based on data are very misleading —- large values look huge. The bike
sharing data set from lecture ran into this problem before I switched from
radius to area.
