### ISSUE TITLE
MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by StevenClontz** [data-8/datascience#426]
When using Matplotlib 3.1, `from datascience import Table` results in the following warnings.

```
/home/user/.local/lib/python3.7/site-packages/datascience/tables.py:17: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('agg', warn=False)
/home/user/.local/lib/python3.7/site-packages/datascience/util.py:10: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('agg', warn=False)
```

**Comment by adnanhemani** [comment]
Hi @StevenClontz , I've madde a PR for a patch. Please let me know if you've got any feedback :)

**Comment by StevenClontz** [comment]
Thanks! I'm toying with using this library for a few introductory data science modules with high school kids in the fall. Any plans to update the PyPI package in the next month or so?

**Comment by adnanhemani** [comment]
Hi @StevenClontz, as of right now, no. But if this is an absolute blocker for you, @davidwagner would be the person to talk to about updating the PyPi version.

**Comment by davidwagner** [comment]
@StevenClontz   Oops, I didn't see this.  I can push an update if it would be helpful - let me know if this is still relevant to you.

**Comment by StevenClontz** [comment]
That'd be nice if possible (although we can just tell them to ignore the
warnings otherwise). I'm developing math activities for a magnet cyber-STEM
high school using Python across the curriculum, and I was planning on using
this library for an introduction to data science. They'll probably get into
it around late September or October.


Steven Clontz
https://clontz.org - steven.clontz@gmail.com
