### ISSUE TITLE
Unexpected indentation in Table.columns docstring

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#443]
`make docs` complains:

```
../datascience/tables.py:docstring of datascience.tables.Table.columns:14: WARNING: Unexpected indentation.
```

I am not sure, but I suspect this might be referring to line 326 or somewhere thereabouts, which was changed in commit 63ab71dc.  Maybe @adityakuppa26 can help?

**Comment by adityakuppa26** [comment]
@davidwagner fixed issue in https://github.com/data-8/datascience/pull/446.

**Comment by adnanhemani** [comment]
Closing issue as code has been merged into master
