### ISSUE TITLE
make test errors out with unrecognized arguments

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#470]
On my Linux machine, `make test` yields the following error message:

```
running build_ext
ERROR: usage: setup.py [options] [file_or_dir] [file_or_dir] [...]
setup.py: error: unrecognized arguments: --nbval-lax --cov=datascience
  inifile: None
  rootdir: /home/daw/datascience/datascience
```

What am I missing about how to make this work?

I have run `pip install -r requirements.txt` so if I'm missing some Python package, then maybe it should be listed in requirements.txt.  I have nbsphinx 0.7.1, nbconvert 5.5.0, nbformat 4.4.0, nbval 0.9.6 installed.

**Comment by adnanhemani** [comment]
Hey, I think I put something about this error here: [https://github.com/data-8/datascience/pull/432#issuecomment-683525521](https://github.com/data-8/datascience/pull/432#issuecomment-683525521)

Does having this library help: `pytest-cov`?

**Comment by hmstepanek** [comment]
I ran into this issue too. I believe this has to do with not including `nbval` and `pytest-cov` libraries in `tests_requires` in `setup.py`:
Current `setup.py`:
```
tests_requires = [
    'pytest',
    'coverage',
    'coveralls',
    'bokeh'
]
```
Fixed `setup.py`:
```
tests_requires = [
    'pytest',
    'coverage',
    'coveralls',
    'bokeh',
    'nbval',
    'pytest-cov'
]
```

**Comment by adnanhemani** [comment]
Interesting - I didn't think that was necessary, but I'm probably wrong. @davidwagner - could you give this a try?

**Comment by davidwagner** [comment]
Oh!  That was exactly the issue.  Sorry that I missed that your earlier comment, @adnanhemani.  Pilot error on my part.

I've been reading about `tests_requires` in setuptools.  Does that even work?  The documentation refers to `tests_require` rather than `tests_requires`.  Apparently `tests_require` is now deprecated as of recent versions of setuptools, and we're not supposed to use `python setup.py test` any longer.  I'm trying to figure out what is the modern method.

Make rather than updating `tests_requires` we should look into converting to the modern way to run tests?  Maybe calling the `pytest` test runner directly?

**Comment by adnanhemani** [comment]
Yup, we should look into that for sure. I haven't had much time recently to take a look at it but maybe we should create a new issue for that and close this issue out if this is resolved? (or maybe I've misread and actually we need changes to the linux_environment.yml file?)

**Comment by adnanhemani** [comment]
Closing out this issue - I believe the changes we made to get Github Actions should suffice for the long-term. Let's keep an eye on our new testing infrastructure for the future :)
