### ISSUE TITLE
Feature Enhancement -  Add tox for testing multiple python versions

### ISSUE THREAD

**Issue by gurupratap-matharu** [data-8/datascience#483]
An awesome feature for this package would be to use a great tool like tox
to automatically  test the package against different python versions.

A PR is linked which does it ;-)

Thank you

**Comment by davidwagner** [comment]
Looks like this is PR #482.  I'm new to tox: can you help me understand what the benefit would be?  Is it common for code to fail on one version of Python and not another?

**Comment by gurupratap-matharu** [comment]
Failing of a package on different python versions depends upon the
complexity of the package.
Since this repo is a pip package we cannot guarantee each user using it
will have the same base python version
we want them to have.
It's great that the package is being tested by unit tests.
Tox simply helps run those tests against different python versions
automatically to assure that the package
is guaranteed to work properly. This enhances the usability.

Tox is pretty popular to test pythonic packages.

Check this excellent python package using it https://github.com/joke2k/faker

**Comment by adnanhemani** [comment]
Closed with #482.
