### ISSUE TITLE
putting a fork of this repo on PyPI

### ISSUE THREAD

**Issue by tbrown122387** [data-8/datascience#492]
I will be teaching an intro stats class in the Spring that makes heavy use of this package. There have been a few very small things I wanted to change, so I created a fork. Really small things--I'm talking "changing the default plotting colors from Berkeley colors" small.

Would it be okay if I put my work on PyPi under a new name? This way my students could install the fork with `pip`. If so, should I remove you all as authors from [`setup.py`](https://github.com/data-8/datascience/blob/master/setup.py) or just add my own name? 

Your [license](https://github.com/data-8/datascience/blob/master/LICENSE) mentions "[n]either the name of `datascience` nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission." I don't plan on promoting this--it's just for an intro class. 

Just wanted to reach out because this is sort of a weird situation. Especially because the ratio of your contributions to my contributions is near infinity.

**Comment by adnanhemani** [comment]
I believe this is a decision above my pay grade 😉 @davidwagner would be able to answer this better.

From my perspective, while I’d prefer that people use the library as-is and contribute if there’s anything that fundamentally needs changing, I think it might be okay to deploy a fork to PyPi given that it is very clearly denoted in the package title that the new package is a fork of the original (ex. “datascience-fork-tbrown”).

Again, I’m not the final decision maker here, but just my $0.02

**Comment by papajohn** [comment]
I think that's fine. Please extend the author list as needed.

**Comment by tbrown122387** [comment]
thanks @papajohn @adnanhemani sure will do!

**Comment by adnanhemani** [comment]
@tbrown122387 marking this issue as closed - please feel free to reopen if there's any action items that are still open 😃
