### ISSUE TITLE
bar and group_bar aren't implemented under Table.interactive_plots() 

### ISSUE THREAD

**Issue by surajrampure** [data-8/datascience#495]
It seems like only `barh` and `group_barh` are supported with plotly for now.
Furthermore, while `ibarh` exists, `igroup_bar` does not, which seems a little inconsistent (and it means that there's no way to access that functionality without running `Table.interactive_plots()` first).

**Comment by davidwagner** [comment]
Thanks, Suraj.  I rely on @chrispyles and @khsu2000 for maintenance or improvements to the interactive plot stuff.  I don't know whether there are any plans to add support for that.  It's beyond my capability to implement that myself.

**Comment by adnanhemani** [comment]
^ +1 to that. @davidwagner and I aren't supporting this part of the library.

**Comment by khsu2000** [comment]
I've created the PR listed above that adds these functions.

**Comment by davidwagner** [comment]
@surajrampure   I've merged this.  Let me know if you'd like me to release and push an updated version of the datascience library to Pypi so you can use this.
