### ISSUE TITLE
Specifying bins as arrays when using `group` and `overlay` with Table.hist and Table.interactive_plots() causes an error

### ISSUE THREAD

**Issue by surajrampure** [data-8/datascience#496]
Sorry for the wordy title. I've attached a screenshot of the issue.

The error doesn't occur if you remove `overlay = False`, or if you specify `bins` to be an integer rather than an array. (`bins` as an array works in all other cases.)

<img width="865" alt="Screen Shot 2021-04-01 at 11 42 13 PM" src="https://user-images.githubusercontent.com/10468713/113378014-ea6c7380-9343-11eb-884a-de015be079af.png">

**Comment by adnanhemani** [comment]
As this is a bug with the interactive plots part of the library, @chrispyles and @khsu2000 are the point of contacts on this.

**Comment by khsu2000** [comment]
Looking into this now.

**Comment by surajrampure** [comment]
Thank you! I’ve identified a few more plotly integration bugs; should I keep opening issues here or is there a more convenient place for me to put them?

>

**Comment by khsu2000** [comment]
I believe the PR I made (#480) that was merged last month resolves this issue. When I install the most recent version of datascience and try the command, I'm able to produce the expected graphs: 
![image](https://user-images.githubusercontent.com/42821828/113543827-0a966f80-959c-11eb-8abb-ecd6a94ffa36.png)
I also verified that using datascience before this PR was merged results in the error that you saw. Using the most up-to-date version of datascience should fix your issue.

**Comment by khsu2000** [comment]
I'm unsure of if there's a more convenient location to list issues, opening new issues should be fine.

**Comment by davidwagner** [comment]
@surajrampure , opening additional issues here for any other plotly integration issues you find would be great!  Thank you.

**Comment by adnanhemani** [comment]
Noting that this issue should now be resolved, I'm going to close this issue. @surajrampure please feel free to open new issues for the plotly integration! :)
