### ISSUE TITLE
Travis integration no longer works

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#508]
Travis shut down travis-ci.org.  Migration is necessary if we want to continue using Travis: https://docs.travis-ci.com/user/migrate/open-source-repository-migration/, https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/.  I've requested OSS credits from Travis.

Alternatively, we could switch to something else, e.g., Github Actions.

**Comment by davidwagner** [comment]
I haven't figured out how to connect my travis-ci.com account to the data-8/datascience Github repo, so I haven't been able to figure out how to migrate to travis-ci.com.

**Comment by adnanhemani** [comment]
Closed by #528. #534 should get us to unblocking the master branch again and be open for new PRs again 🎉
