### ISSUE TITLE
Labels do not appear on map markers when using map_table

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#510]
Passing a three-column table to `map_table` is meant to place markers on a map with labels that appear when clicking on a marker. E.g., from https://inferentialthinking.com/chapters/08/5/Bike_Sharing_in_the_Bay_Area.html

`Marker.map_table(stations.select('lat', 'long', 'name'))`

However, the labels are blank in the map (despite being present in the data). Perhaps `folium` changed its API.

**Comment by khsu2000** [comment]
I believe this should is the same problem as https://github.com/data-8/datascience/issues/509, where `'name'` should be changed into `'labels'`.

**Comment by davidwagner** [comment]
Same as khsu2000 explained -- This looks like it's not a bug in the `datascience` library, but rather a bug in the textbook.  The docs for `Marker.map_table` say that the column name must be `labels` (`name` is not OK).  See http://data8.org/datascience/maps.html#datascience.maps.Marker.map_table.
