### ISSUE TITLE
Table.remove() converts columns into lists

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#513]
When using `Table.remove()`, the type of the columns in a table become lists.  They should remain arrays.  See attached notebook for an example.

[TableRemoveOddity.zip](https://github.com/data-8/datascience/files/7174805/TableRemoveOddity.zip)

Sample code to reproduce:

```
>>> newTable = Table().with_columns(
        "Teams", make_array('Aces', 'Bears', 'Cats', 'Dogs', 'Eagles', 'Ferrets'),
        "Scores", make_array(93, 87, 92, 75, 96, 68)
    )
>>> newTable.remove(0)
>>> newTable.column('Scores')
[87, 92, 75, 96, 68]
>>> type(newTable.column('Scores'))
list
```

Looking at the implementation of `.remove()` (https://github.com/data-8/datascience/blob/master/datascience/tables.py#L1118), we can immediately see the problem:

```
for col in self._columns:
            self._columns[col] = [elem for i, elem in enumerate(self[col]) if i not in rows_remove]
```

It creates a list, not an array.   I believe this should be fixed to create an array.

(Seeing as `.remove()` is also side-effecting and we are trying to promote non-side-effecting methods where appropriate, we could consider deprecating `.remove()` anyway and pointing people to `.exclude()`.)

Thanks to Dan Kaiser for this bug report.

**Comment by abhishict** [comment]
I've fixed this issue in the above pull request, could you please review and approve. Thanks!
