### ISSUE TITLE
Datascience documentation has a typo 

### ISSUE THREAD

**Issue by CharlieJCJ** [data-8/datascience#519]
![image](https://user-images.githubusercontent.com/55744150/141862800-5004bb22-ca87-44c2-b2f4-2bbeb31e7a23.png)

(I'm a current Data8 student), and when I'm reviewing the documentation of barh, I found a typo in the documentation. "furniture_table" is not defined yet. Thanks!

**Comment by CharlieJCJ** [comment]
Any updates on this issue? I still can see the typo on the website.
link: http://data8.org/datascience/_autosummary/datascience.tables.Table.barh.html#datascience.tables.Table.barh

**Comment by Ruofeng-Wang** [comment]
I think I’ve updated the code and just waiting for my pr to be approved.

**Comment by davidwagner** [comment]
Should be fixed by #524.  Sorry for the delay.
