### ISSUE TITLE
Upload a wheel to PyPI

### ISSUE THREAD

**Issue by yuvipanda** [data-8/datascience#522]
Currently, only an `sdist` (.tar.gz) is [uploaded to PyPI](https://pypi.org/project/datascience/#files). This means we can't install this package on [jupyterlite](https://jupyterlite.readthedocs.io/en/latest/), a fully fledged jupyter installation running python and the scientific stack just on your browser! It can install only pure python wheels, and I think the datascience package fits that bill.
 
This should be fairly easy to do:

```bash
pip install wheel
python setup.py bdist_wheel upload
(enter pypi password when asked)
```

/cc @ericvd-ucb who is interested in getting data-8 connectors and friends to try out jupyterlite.

**Comment by ericvd-ucb** [comment]
@data-8/infra-fall21  can we put this on the list!

**Comment by yuvipanda** [comment]
Just fixed!
