### ISSUE TITLE
v0.17.5 not pip installable

### ISSUE THREAD

**Issue by taylorgibson** [data-8/datascience#548]
Is there a timeline for pushing the latest release, `0.17.5` to pypi? The latest version that is installed when running `pip install datascience` is `0.17.2` which is not compatible with python 3.10+ due to the deprecation of `collections.Iterable`. Thanks!

**Comment by adnanhemani** [comment]
Hi Taylor, sorry for the delay - we've been busy trying to get the library ready for our next release :) I believe we have just one more PR under works/review (#500), which adds a bug fix to the 0.17.5 release. After we merge that in, I believe @davidwagner will be able to release v0.17.5.

I'll let @davidwagner comment on if there's any further delays/issues that I'm not aware of.
