### ISSUE TITLE
Switch to Bokeh for charts?

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#55]
Bokeh now supports Python 3. The charts that are rendered support zooming and look nice. (Their mapping functionality looks less useful than folium, though.)

**Comment by a-adhikari** [comment]
Bokeh charts look great! Happy to support whatever you think is feasible.
Ani

**Comment by elaine84** [comment]
We would love to see this functionality for the geospatial connector for KDE mapping

**Comment by papajohn** [comment]
I tried to implement our current behavior using `bokeh`, but the following Bokeh issues will need to be resolved first.

Density doesn't work: https://github.com/bokeh/bokeh/issues/3576
Bins is inflexible: https://github.com/bokeh/bokeh/issues/3398
No histogram from counts: https://github.com/bokeh/bokeh/issues/3842

**Comment by a-adhikari** [comment]
Thanks for testing this out, John. Indeed, those issues are critical :)
Ani

On Sun, Feb 7, 2016 at 11:20 AM, John DeNero <notifications@github.com>
wrote:

> I tried to implement our current behavior using bokeh, but the following
> Bokeh issues will need to be resolved first.
>
> Density doesn't work: bokeh/bokeh#3576
> <https://github.com/bokeh/bokeh/issues/3576>
> Bins is inflexible: bokeh/bokeh#3398
> <https://github.com/bokeh/bokeh/issues/3398>
> No histogram from counts: bokeh/bokeh#3842
> <https://github.com/bokeh/bokeh/issues/3842>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/data-8/datascience/issues/55#issuecomment-181088715>.
>



-- 
Ani Adhikari
Teaching Professor
Department of Statistics
University of California, Berkeley

**Comment by ryanlovett** [comment]
https://bids.berkeley.edu/events/telling-your-data-story-bokeh

Fyi, there's an upcoming BIDS talk on Bokeh by one of its core developers.


Ryan
