### ISSUE TITLE
Getting warning from numpy when creating pivot table

### ISSUE THREAD

**Issue by sean-morris** [data-8/datascience#550]
The following screenshot illustrates the VisibleDeprecationWarning we are getting from numpy when creating a pivot table using the datascience package.
![image](https://user-images.githubusercontent.com/1514995/183722948-b970c722-e770-468c-88c1-3ad6359d836a.png)

Here is a StackOverflow entry discussing the issue:
https://stackoverflow.com/questions/63097829/debugging-numpy-visibledeprecationwarning-ndarray-from-ragged-nested-sequences

Essentially you need to specify `dtype=object`  in what appears to be the `append` function in tables.py.

**Comment by davidwagner** [comment]
What version of the datascience library are you using?  I think we fixed several issues of this sort in v0.17.5 (fixed in PR #458, also reported in #514 and #458).  Or is there another one of these that we missed?

**Comment by adnanhemani** [comment]
Yup, this is the exact errors I had seen before fixing it in the latest version of datascience, as mentioned by @davidwagner. I’ll mark this as closed for now, please feel free to comment back with steps for reproduction using the latest version of datascience if it is still occurring for you and re-open the ticket!

Thanks for the report!

**Comment by sean-morris** [comment]
Yes thanks I upgraded to 0.17.5 and this went away. Unfortunately, I think I spotted another one:
![image](https://user-images.githubusercontent.com/1514995/184041202-47cb400f-91f1-46de-ab81-0b8bbca3af1a.png)

I looked through PR's and did not see this one. Should this reported separately or reopen here?

**Comment by davidwagner** [comment]
Thank you!  Could you submit a new issue with enough information that we can reproduce it, @sean-morris?
