### ISSUE TITLE
getting version in setup.py

### ISSUE THREAD

**Issue by zahash** [data-8/datascience#556]
https://github.com/data-8/datascience/blob/67ff872edb590d7c2cfab93bbc14b3132b263117/setup.py#L20-L24

why not use a simpler approach to just import __version__ from the version.py file?

`from datascience.version import __version__ as version`

**Comment by Divyanshu9676** [comment]
Hey, I am new to Open Source and I would like to contribute to this.

**Comment by davidwagner** [comment]
@zahash Will that get the version of the currently installed datascience package (which might be an older version) rather than the version of the code this is working with?

**Comment by adnanhemani** [comment]
@davidwagner I'm not sure I'm following the concern here? If we import the version number directly from this file rather than reading the actual file, what could go wrong? From my understanding, it should be the exact same version number.

**Comment by davidwagner** [comment]
@adnanhemani   You're right, I don't think I was thinking clearly.  The simpler approach makes sense to me.

**Comment by adnanhemani** [comment]
Update on the issue: I think we tried this but this actually causes a circular dependency when setting up the repository. We've marked this off the corresponding PR. If there are any thoughts on this topic, please feel free to re-open this issue with additional findings.
