### ISSUE TITLE
We use Python f-strings

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#559]
The code uses f-strings (tables.py:3161, maps.py:129, and some test code), which requires Python 3.6, but we only check for Python 3.0.

Should we update the checks to require Python 3.6, or should we remove the f-strings so this works with Python 3.0?

**Comment by davidwagner** [comment]
@adnanhemani I'd be interested to hear your thoughts on this.  (See also #555.)

**Comment by adnanhemani** [comment]
I think we should go ahead and update to use Python 3.6 - most of the library was developed and first deployed using Python 3.6+.

Here's my recommendation - let's update the library version by a medium version (up to 0.18.0, I believe) and then make Python 3.6.0 the minimum required version. I'll make a comment on the PR for this.

**Comment by davidwagner** [comment]
Done - see #564
