### ISSUE TITLE
bokeh required for tests to pass

### ISSUE THREAD

**Issue by taylorgibson** [data-8/datascience#579]
I just went through the instructions in `DEVELOPERS.md` and when running `make test` 115 tests failed because `bokeh` was not installed in the environment. 

![image](https://user-images.githubusercontent.com/5053805/217902548-098ec613-89c4-4e78-b736-1fd7d65ec683.png)

Installing `bokeh` allows all 346 tests to pass (2 warnings). 

![image](https://user-images.githubusercontent.com/5053805/217902624-80781244-fb4f-4ea5-86e0-99fdbab1bf88.png)

`bokeh` should be added to the `osx_environment.yml` and `linux_environment.yml` if it is required for the tests to pass.

**Comment by adnanhemani** [comment]
Hi, placing comments onto your PR.

**Comment by davidwagner** [comment]
Thank you for reporting this!  Based on the discussion in #580, my sense is that the best short-term solution might be to update DEVELOPERS.md to mention the dependence on `requirements-tests.txt`.  Moving to tox sounds like a longer-term project.  But I don't have strong opinions and I expect I'll be glad to go with whatever you and Adnan come up with.
