### ISSUE TITLE
Do we need to check for `collections.abc.Sequence` in `utils. is_non_string_iterable`?

### ISSUE THREAD

**Issue by adnanhemani** [data-8/datascience#584]
Question here for @davidwagner and/or @papajohn - or anyone else that has knowledge on the topic:

Referencing this piece of code: https://github.com/data-8/datascience/blob/master/datascience/util.py#L255-L257

Do we even need the check for if the value is of type `collections.abc.Sequence`? From the [documentation](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence), `collections.abc.Sequence` has `__iter__` defined as a mixin automatically - and so any code check on whether the value has the `__iter__` attribute is always coming back `true` (I have yet to find a way to make this check return false for a Sequence typed object - if anyone has any thoughts on how to do this, please comment).

Looking through the code history, it seems like this check for Sequence type was made before we started checking for iterable objects so it may just be dead code that's stuck around over the years without thought. (I only found it due to a PR that was raising a test for this LOC but no matter what, the test wasn't hitting the exact condition on Coveralls prompting me to investigate what was going on). Does anyone have any ideas if this code is even useful anymore? Are there any objections to me raising a PR to wipe out the additional condition (to check for a Sequence typed object) if it's simply dead code?

**Comment by papajohn** [comment]
I agree that it looks redundant to check for __iter__ and check the type.
Just check for __iter__.

**Comment by davidwagner** [comment]
Fixed now in PR #585.  Thank you for catching this!
