### ISSUE TITLE
Please restore: column_labels in 0.17.5 versus 0.17.6

### ISSUE THREAD

**Issue by sean-morris** [data-8/datascience#592]
In the latest release of datascience, the Table class property column_labels was removed and replaced by labels.

I know there was a deprecation warning in place. 

The issue is that in JupyterLite we can not load the 0.17.5 because there is no wheel defined for this release in pypi.org.

You can see the difference here:
https://pypi.org/project/datascience/0.17.6/#files

versus here:
https://pypi.org/project/datascience/0.17.5/#files

I am not sure if we can build a wheel on 0.17.5 or just bring back column_labels.

Thanks,

Sean

**Comment by ericvd-ucb** [comment]
@amoghkokari 
  Could you please help with this? Seems like we have problems with notebooks we have shared with community colleges due to a commit you made in January.  LMK if you need more documentation

**Comment by davidwagner** [comment]
@sean-morris @ericvd-ucb Sorry about the headaches. I've uploaded a binary wheel for 0.17.5.  Does this address your needs?  Note that you'll probably want to update your notebooks so that it works with the latest version at some point, as development will continue from the latest version.

**Comment by sean-morris** [comment]
@davidwagner Yes, we can update our notebooks. I don't see a list of the actual deprecation changes from 0.17.5 to 0.17.6. Is there a list that I am missing somewhere?

**Comment by sean-morris** [comment]
@davidwagner Thanks. I also noticed that Table#cumsum() function was changed? Although I can't tell if maybe this is coming from somewhere else in the package.

**Comment by adnanhemani** [comment]
Hi @sean-morris - there's a thread about this on a different repo: https://github.com/data-8/textbook/issues/180#issuecomment-1605181175

I don't think we're bringing back the deprecated function to be honest unless there's a very good reason to do so. Let us know if you have any thoughts!
