### ISSUE TITLE
Support stacked bar charts & histograms

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#6]

**Comment by papajohn** [comment]
@a-adhikari is interested in stacking histograms to write the total variation distance chapter.

**Comment by SamLau95** [comment]
This is sorta closed by https://github.com/dsten/datascience/pull/84 . Do we also need stacked bar charts? Or is having stacked histograms enough?

**Comment by deculler** [comment]
Stacked bars are easy and pretty common.  Most of us use them a fair amount
in excel.  But you can probably get them already with the right kwarg.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by papajohn** [comment]
I think this issue is not resolved. We have overlain hist, but not stacked
hist or stacked bar charts, and we should have both of those some day.

**Comment by adnanhemani** [comment]
I believe this is currently possible through passing in `stacked=True` into the `hist` or `bar(h)` functionalities. Is there something additional to implement here? Or do we require explicit support by adding this to the method signatures or docs? Or something else? Sorry, just trying to figure out what the gap here is.

**Comment by samanth2012** [comment]
> _No description provided._

Hello iam beginner I learnt python please guide me how to contribute to open source

**Comment by adnanhemani** [comment]
Since this issue is stale and has been open for many years (~1 year without a comment), I'm going to make this as closed due to the above findings. Please feel free to reopen with any additional information.
