### ISSUE TITLE
Feature request: way to create a heat map from a Table of (lat,long) points

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#69]
It would be nice if the Map class provided a way to overlay a heat map on top of a map: given a large collection of (lat,long) points (e.g., Markers), construct a heat map making it easy to visualize where the points are most concentrated. 

Maybe there's an easy way by using the options provided, but I couldn't figure out how to do that from the public documentation.  Maybe provide an API for this, or document how to do it?  I bet this will be a useful thing for students -- and I'd like to use it for Friday lecture too.

**Comment by papajohn** [comment]
There's no heatmap support in the mapping library we're using, as far as I can tell. You can draw a bunch of transparent circles, which gives  a similar effect — opacity is a measure of concentration.

For example, the parcels of Berkeley vaguely look like a heat map:

![screen shot 2015-09-17 at 10 35 16 pm](https://cloud.githubusercontent.com/assets/320145/9946637/6967c908-5d8c-11e5-940e-b8ccb84392a0.png)

**Comment by alvinwan** [comment]
I don't know if this helps, but here's [heatmap.js](http://www.patrick-wied.at/static/heatmapjs/showcases.html) integrated with Google Maps. http://www.crimeheatmap.ca/#

<img width="1272" alt="screen shot 2015-09-17 at 2 49 19 pm" src="https://cloud.githubusercontent.com/assets/2068077/9946915/51039bf8-5d4b-11e5-933a-11d9f8613b0d.png">

**Comment by davidwagner** [comment]
Thanks!  Note to self: if I've got too much data for heatmap.js, I should also check out [webgl-heatmap](http://codeflow.org/entries/2013/feb/04/high-performance-js-heatmaps/).

I skipped doing this for the privacy lecture, but it could be fun to show people how to construct a heatmap in a future semester and students might find it a helpful way to visualize data.  Especially if it's just a method on Table (Table.heatmap('latitude', 'longitude')).  So consider this a candidate enhancement to the datascience library for some unspecified point in the future. :-)

**Comment by pattyf** [comment]
The latest version of folium has a heatmap plugin. I've tested it with a file of 23,000 points and it works well/fast. See attached zipfile for example.  It would be great to upgrade to the newer version of folium.
[crime_heatmap.zip](https://github.com/data-8/datascience/files/355745/crime_heatmap.zip)

**Comment by ryanlovett** [comment]
Looks like datascience has a [hard dependency](https://github.com/data-8/datascience/blob/master/requirements.txt#L1) on folium 0.1.5. @papajohn or @SamLau95, do you know if using folium 0.2.x would break datascience?

**Comment by papajohn** [comment]
Probably, but we will just need to update datascience to use whatever
interface changes have been published for folium since the previous
version. I don't think it's a lot of work. Certainly we could get it done
before August.

**Comment by pattyf** [comment]
FYI attached is an example notebook & html file of a heatmap of 600,000 license plate reader points. It can also create a heatmap from 3 million points but slow to create and view in browser. 
[licplate_heatmap.zip](https://github.com/data-8/datascience/files/356357/licplate_heatmap.zip)

**Comment by davidwagner** [comment]
With the benefit of time, this doesn't seem like a priority to me any more.
